export function amenityLabel(key: string, locale: string) {
  const map: Record<string, { en: string; fr: string }> = {
    meals: { en: "Meals included", fr: "Repas inclus" },
    garden: { en: "Food garden", fr: "Jardin potager" },
    outdoor: { en: "Daily outdoor block", fr: "Bloc extérieur quotidien" },
    inclusive: { en: "Inclusive practice", fr: "Pratique inclusive" },
    music: { en: "Music program", fr: "Programme de musique" },
    atelier: { en: "Atelier / studio", fr: "Atelier" },
    walks: { en: "Neighbourhood walks", fr: "Promenades de quartier" },
    documentation: { en: "Weekly learning stories", fr: "Histoires d'apprentissage" },
    bilingual: { en: "Bilingual program", fr: "Programme bilingue" },
    extended: { en: "Extended hours", fr: "Heures prolongées" },
    "infant-room": { en: "Infant program", fr: "Programme nourrissons" },
    nature: { en: "Nature-based", fr: "Pédagogie nature" },
    wool: { en: "Wool layers on site", fr: "Couches de laine sur place" },
    "mud-kitchen": { en: "Mud kitchen", fr: "Cuisine de boue" },
    licensed: { en: "Licensed", fr: "Permis" },
    home: { en: "Home-scale", fr: "Échelle familiale" },
    yard: { en: "Fenced yard", fr: "Cour clôturée" },
    "small-group": { en: "Max 8 children", fr: "Max. 8 enfants" },
    gym: { en: "Gym access", fr: "Accès au gymnase" },
    subsidy: { en: "Subsidy-friendly", fr: "Adapté à la subvention" },
    chef: { en: "Teaching kitchen", fr: "Cuisine pédagogique" },
    literacy: { en: "Literacy-forward", fr: "Littératie" },
    tours: { en: "Thursday tours", fr: "Visites le jeudi" },
    "sliding-scale": { en: "Sliding-scale fees", fr: "Tarif selon le revenu" },
    "resource-centre": { en: "Family resource centre", fr: "Centre de ressources" },
    park: { en: "Beside a park", fr: "À côté d'un parc" },
    transit: { en: "On a bus route", fr: "Sur une ligne d'autobus" },
    "mixed-age": { en: "Mixed-age afternoons", fr: "Après-midis multiâges" },
    fob: { en: "Fob entry", fr: "Accès par fob" },
    app: { en: "Parent app", fr: "Appli parents" },
    woodland: { en: "Woodland lot", fr: "Lot boisé" },
    walkable: { en: "Walkable", fr: "Accessible à pied" },
    bakery: { en: "Above a bakery", fr: "Au-dessus d'une boulangerie" },
    commuter: { en: "Commuter-friendly", fr: "Pratique pour les navetteurs" },
    bread: { en: "Friday baking", fr: "Cuisson du vendredi" },
    "open-spots": { en: "Spots open now", fr: "Places ouvertes" },
    "new-build": { en: "New building", fr: "Nouveau bâtiment" },
    community: { en: "Community-run", fr: "Géré par la communauté" },
    urban: { en: "Urban studio", fr: "Studio urbain" },
    funded: { en: "Provincially funded", fr: "Financé par la province" },
    unfunded: { en: "Non-funded", fr: "Non financé" },
    "ten-a-day": { en: "$10-a-day program", fr: "Programme 10 $ par jour" },
    "for-profit": { en: "For-profit", fr: "À but lucratif" },
    nonprofit: { en: "Non-profit", fr: "Sans but lucratif" },
    preschool: { en: "Preschool", fr: "Préscolaire" },
    nursery: { en: "Nursery", fr: "Garderie (nursery)" },
    "school-age": { en: "School-age care", fr: "Service parascolaire" },
    "in-school": { en: "In a school", fr: "Dans une école" },
    french: { en: "French-language", fr: "Francophone" },
    evenings: { en: "Evening care", fr: "Soirs" },
    weekends: { en: "Weekend care", fr: "Fins de semaine" },
    montessori: { en: "Montessori", fr: "Montessori" },
    ymca: { en: "YMCA-YWCA", fr: "YMCA-YWCA" },
  };
  return map[key]?.[locale === "fr" ? "fr" : "en"] ?? key;
}
