import type { Locale } from "./types";
import { extraCopy } from "./extra-copy";

export const copy = {
  en: {
    app: "KidEase",
    tagline: "Find licensed daycare near you",
    search: "Search",
    explore: "Explore",
    benefitsTab: "Childcare Benefits Program",
    benefitsShort: "Childcare Benefits Program",
    benefitsTitle: "Help paying for care",
    benefitsLead:
      "Most reduced fees under the Canada-Wide Early Learning and Child Care program are applied automatically at participating daycares. Extra help for lower-income families (fee subsidies) is a separate application, and it works differently in every province.",
    benefitsApply: "Apply on the official site",
    benefitsBcT: "British Columbia",
    benefitsBc: "Affordable Child Care Benefit — apply through My Family Services.",
    benefitsMbT: "Manitoba",
    benefitsMb: "Child Care Subsidy for eligible families using licensed care.",
    benefitsAbT: "Alberta",
    benefitsAb: "Child Care Subsidy (for school-age) + Affordability Grant / $15-a-day fees for younger children.",
    benefitsOnT: "Ontario",
    benefitsOn: "Fee subsidy is managed locally. Find your CMSM or DSSAB.",
    benefitsQcT: "Quebec",
    benefitsQc: "Reduced contribution spaces and the childcare tax credit through Revenu Québec.",
    benefitsFedT: "Canada Child Benefit",
    benefitsFed: "Federal monthly payment for eligible families.",
    benefitsSkT: "Saskatchewan",
    benefitsSk:
      "$10-a-day regulated child care for children under 6. Low-income families may also access support through the Saskatchewan Employment Incentive.",
    benefitsNsT: "Nova Scotia",
    benefitsNs: "Reduced parent fees + Nova Scotia Child Care Subsidy Program for eligible families.",
    benefitsNbT: "New Brunswick",
    benefitsNb: "Parent Subsidy Program and Childcare Assistance Program for eligible families.",
    benefitsPeT: "Prince Edward Island",
    benefitsPe: "$10-a-day regulated child care + Child Care Subsidy Program.",
    benefitsNlT: "Newfoundland and Labrador",
    benefitsNl: "$10-a-day regulated child care + Child Care Subsidy Program.",
    benefitsYtT: "Yukon",
    benefitsYt: "Universal child care program (average $10-a-day) + Child Care Subsidy.",
    benefitsNtT: "Northwest Territories",
    benefitsNt: "Child Care Fee Reduction Subsidy (average $10-a-day) + possible Income Assistance support.",
    benefitsNuT: "Nunavut",
    benefitsNu: "$10-a-day regulated child care + Daycare Subsidy for eligible families.",
    benefitsNote: "KidEase does not process these applications. Official government sites open in a new tab.",
    saved: "Saved",
    enrolled: "Enrolled",
    messages: "Messages",
    profile: "Profile",
    inbox: "Inbox",
    account: "Account",
    provider: "Provider",
    signIn: "Sign in",
    signOut: "Sign out",
    continueGoogle: "Continue with Google",
    continueX: "Continue with X",
    continueApple: "Sign in with Apple",
    orEmail: "or use email",
    email: "Email",
    password: "Password",
    name: "Name",
    createAccount: "Create account",
    haveAccount: "Already have an account? Sign in",
    needAccount: "Need an account? Create one",
    loginLead: "Save centres, request a spot, and message educators.",
    loginLeadParent: "Create your parent account to search, save centres, and request a spot.",
    loginLeadProvider: "Create your provider account to claim your listing and manage spots and fees.",
    roleHeadline: "Find the perfect daycare near you",
    roleLead: "Choose how you’ll use KidEase. You can switch later from your account.",
    imParent: "I’m a Parent",
    imProvider: "I’m a Daycare Provider",
    alreadyAccount: "Already have an account?",
    logIn: "Log in",
    parentSignIn: "Parent Sign In",
    providerSignIn: "Provider Sign In",
    useLocation: "Use my location",
    locating: "Getting your location…",
    presenceLive: "Live location",
    presenceFresh: "Location just updated",
    presenceStale: "Using last known location",
    liveInArea: "{n} live on KidEase in this area",
    locationPh: "Address, city, or postal code",
    radius: "Radius",
    km: "km",
    mi: "mi",
    unitsKm: "km",
    unitsMi: "mi",
    distanceUnit: "Distance",
    miAway: "mi away",
    locationConsentTitle: "Show licensed daycares near you",
    locationConsentBody:
      "KidEase uses your precise location only while you search. We never request background location.",
    locationConsentAllow: "Use precise location",
    locationConsentLater: "Not now",
    locationWhileUsing: "Precise location while using KidEase",
    map: "Map",
    mapRoad: "Map",
    mapSat: "Satellite",
    list: "List",
    sort: "Sort",
    filters: "Filters",
    sortDistance: "Distance",
    sortPrice: "Price",
    sortRating: "Rating",
    sortOpen: "Open spots",
    anyAge: "Any age",
    infant: "Infant",
    toddler: "Toddler",
    preschool: "Preschool",
    schoolAge: "School age",
    agesUnknown: "Ages not confirmed",
    agesAccepted: "Ages accepted",
    agesShort: "Ages",
    agesLead: "This shows on your public listing so parents can see who you take. Use months (e.g. 12 to 60).",
    ageMin: "Youngest (months)",
    ageMax: "Oldest (months)",
    monthlyFrom: "from",
    month: "/mo",
    spots: "spots open",
    spotsAvailable: "Spots available",
    waitlist: "Waitlist",
    licensed: "Licensed",
    live: "Live",
    liveBadge: "Live on KidEase",
    notOnKidEase: "Not yet on KidEase",
    liveOnly: "Live Listings",
    showAll: "All listings",
    unclaimedNotice: "This daycare hasn’t joined KidEase yet. You can still view their basic information.",
    unclaimedLead: "Details below come from public records. Pricing and spots may not be current.",
    requestUnavailable: "You’ll be able to request a spot when this centre goes live.",
    noLiveResults: "No live centres in this radius yet. Show all listings, or widen the search.",
    reviews: "reviews",
    googleReviews: "Google",
    readGoogleReviews: "Read Google reviews",
    noResults: "No licensed centres in this radius. Widen the circle or try another city.",
    featured: "Near you",
    recentlyViewed: "Recently viewed",
    availableNow: "Daycares available",
    availableNextMonth: "More centres nearby",
    how: "How it works",
    how1t: "Search by address or GPS",
    how1: "Enter an address, city, or postal code, or use your location. Results sort by distance from you — switch km or miles in Filters.",
    how2t: "Compare the details",
    how2: "Hours, ages, monthly fees, and the licence record — side by side.",
    how3t: "Book a tour or request a spot",
    how3: "Reach the centres that fit your family, in one conversation.",
    bilingual: "English and French",
    language: "Language",
    claimTitle: "Claim your daycare",
    claimLead: "Find the listing we already have from public records and Google, then verify you run it. No duplicate pages.",
    claimSearchPh: "Centre name, address, or licence number",
    claimThis: "Claim this listing",
    alreadyClaimed: "Already claimed",
    claimEmpty: "Start typing a name, address, or city — matches appear as you type.",
    claimNoMatch: "No matching centres. Check the spelling, or list a new centre below.",
    claimMissing: "Can’t find your centre?",
    verifyListing: "Verify this listing",
    verifyLead: "Confirm you manage",
    claimCodeSent: "Your claim code (also sent by email / SMS)",
    claimCodeHint: "Enter the code we sent to your email (and SMS when we have a number).",
    claimCode: "Claim code",
    licensePhoto: "Photo of your daycare licence",
    finishClaim: "Verify and take over",
    claimVerified: "Listing claimed. You can update spots, fees, and photos.",
    claimOwned: "This listing is already on your account.",
    claimFailed: "Could not claim that listing.",
    photoTooBig: "Please choose a photo under 1.5 MB.",
    storefrontPhoto: "Storefront photo",
    storefrontLead:
      "Upload a clear photo of your entrance or storefront so parents can recognize the building. This replaces the street-view photo on your listing.",
    storefrontHint: "Use a well-lit shot of the front door or signage. JPG or PNG under 1.5 MB.",
    storefrontCta: "Upload storefront photo",
    promoteTitle: "Promote this listing",
    promoteLead:
      "Pay to appear at the top of search results near you. Priority listings show a glowing blue Priority badge so parents notice you first.",
    promoteWeek: "7 days",
    promoteMonth: "30 days",
    promoteQuarter: "90 days",
    promotePay: "Promote listing",
    promoteExtend: "Extend priority",
    promoteActive: "Priority placement is on until",
    promoteSecure: "Secure card payment. Priority starts immediately after checkout.",
    priority: "Priority",
    contactEmail: "Business email",
    businessDetails: "Business details",
    claimCta: "Claim your daycare",
    claimCtaLead: "If you run a licensed centre already on KidEase, claim the listing and set your spots and monthly fees.",
    isThisYours: "Is this your centre?",
    claimedBadge: "Claimed",
    pendingClaim: "Verification pending",
    uploadNew: "Replace photo",
    phoneLabel: "Phone",
    cityLabel: "City",
    provinceLabel: "Province",
    postalLabel: "Postal code",
    addressLabel: "Street address",
    privacyNote: "Built for Canadian families. We do not sell children’s data.",
    privacy: "Privacy",
    viewListing: "View listing",
    book: "Request a spot",
    message: "Message",
    save: "Save",
    savedDone: "Saved",
    call: "Call",
    video: "Video check-in",
    hours: "Hours",
    ages: "Ages accepted",
    months: "months",
    license: "Licence",
    pricing: "Monthly parent fees",
    infantFee: "Infant",
    toddlerFee: "Toddler",
    preschoolFee: "Preschool",
    partTime: "Part-time",
    fullTime: "Full-time",
    availability: "Open spots by month",
    about: "About",
    amenities: "What they offer",
    parentReviews: "Parent reviews",
    similar: "Also nearby",
    back: "Back",
    startMonth: "Start month",
    schedule: "Schedule",
    child: "Child",
    addChild: "Add a child",
    childName: "Child’s first name",
    birthdate: "Birthdate",
    notes: "Notes for educators",
    submitRequest: "Send request",
    needSignIn: "Sign in to request a spot.",
    requestSent: "Request sent",
    requestWait: "Added to the waitlist",
    dashboard: "Your family",
    bookings: "My requests",
    payments: "Payments",
    children: "Children",
    noBookings: "No enrolment requests yet.",
    noPayments: "No payments yet.",
    noPaymentsLead: "Payments appear after a centre offers you a spot. Nothing is charged until then.",
    noChildren: "Add a child to speed up requests.",
    noChildrenLead: "A short profile (name, birthdate, allergies) goes with every request.",
    noSaved: "No saved centres yet.",
    noSavedLead: "Save a listing from search, then request a spot or send a child profile.",
    noInbox: "No messages yet.",
    noInboxLead: "A thread opens when you request a spot or a centre replies.",
    deskHome: "Home",
    deskHomeTitle: "Your family desk",
    deskHomeLead: "Search licensed care, reopen saved centres, track requests, and message educators — in one place.",
    deskHomeSearch: "Find licensed daycares near you.",
    deskHomeSaved: "Centres you want to come back to.",
    deskHomeBookings: "Spot requests and offers.",
    deskHomeInbox: "Messages with centres you contacted.",
    emptyFindCare: "Find care",
    emptyAddChild: "Add a child",
    emptyClaimCentre: "Claim a centre",
    emptyListCentre: "List a centre",
    comparePickMore: " — pick one more",
    compareCount: "Comparing {n} centres",
    mailSendFailed: "Could not send. Email kyle@kidease.ca directly.",
    checkInConsent: "Camera and microphone stay on this device. Start only when you are ready.",
    checkInStart: "Start camera",
    checkInPreview: "Preview only — this is not a live call with the centre yet.",
    verifyHowTitle: "How we verify listings",
    verifyHow1: "Every public listing starts from a provincial or territorial licensed-care register. Unlicensed care is not listed.",
    verifyHow2: "A provider claims the existing page, uploads a current licence photo, and waits for KidEase review. We approve, ask for more, or decline — with a note you can see.",
    verifyHow3: "Live listings show fees and spots the provider entered. Unclaimed pages show registry basics only, never an invented price.",
    verifyHow4: "QA fixtures and test labs are hidden from search, maps, and public URLs. If a listing looks wrong, email kyle@kidease.ca.",
    faqTitle: "Frequently asked questions",
    faqLead: "Short answers for parents and licensed centres. Need a person? Write kyle@kidease.ca.",
    faqQ1: "Do I need an account to search?",
    faqA1: "No. Guests can search the map, open a listing, compare centres, and send a contact note. Sign in when you want to save, request a spot, or message a live centre.",
    faqQ2: "How do you use my location?",
    faqA2: "Only while you search, and only after you allow it. We never request background location. You can always type an address, city, or postal code instead.",
    faqQ3: "What does Live mean?",
    faqA3: "The centre has claimed the listing and KidEase has approved it. Fees and open spots come from the provider. Unclaimed pages are still licensed — details may be out of date.",
    faqQ4: "How do I claim my daycare?",
    faqA4: "Open Claim your daycare, find the existing listing, enter the verification code we send, and upload the current provincial licence. We review every claim.",
    pendingHonesty: "Pending totals are not settled.",
    requestInfo: "Request info",
    lastReviewed: "Reviewed",
    activityAll: "All activity",
    locationPrivacyLink: "How we use location",
    pay: "Pay now",
    payTitle: "Secure your spot",
    payLead: "Payment is only available after the daycare approves your request. You’ll see the exact amount before you confirm.",
    payFor: "First-month parent fee",
    payWhat: "What you’re paying",
    paySecureNote: "Processed securely. We support cards, Apple Pay, and Google Pay.",
    stripeMark: "Secure payments powered by Stripe",
    receiptTitle: "Payment receipt",
    receiptLead: "A copy is saved in your account and sent to the daycare.",
    viewReceipt: "View receipt",
    awaitingPay: "Awaiting parent payment",
    paymentReceived: "Payment received",
    notApprovedPay: "Payment opens after the daycare offers you a spot.",
    printReceipt: "Print receipt",
    paidTo: "Paid to",
    receiptNo: "Receipt",
    amount: "Amount",
    method: "Method",
    card: "Credit or debit",
    apple: "Apple Pay",
    google: "Google Pay",
    paypal: "PayPal",
    interac: "Interac e-Transfer",
    payNow: "Confirm payment",
    paid: "Paid",
    pending: "Pending",
    cardNumber: "Card number",
    expiry: "Expiry",
    cvc: "CVC",
    interacHint: "We’ll show a reference to send from your bank. In this demo the payment is marked pending, then paid.",
    writeMessage: "Write a message",
    send: "Send",
    sms: "SMS",
    voice: "Voice",
    videoCall: "Video",
    checkInTitle: "Check-in room",
    checkInLead: "A private room with the centre. Your camera stays on this device. The centre feed is the classroom overview they published — never a hidden camera on a child.",
    mute: "Mute",
    camera: "Camera",
    end: "End",
    match: "Ask Grok to match",
    matchPh: "e.g. infant, bilingual, $10-a-day, near my neighbourhood",
    matchGo: "Find matches",
    matchNeed: "Describe the care you need",
    providerTitle: "Your centre",
    providerLead: "Update capacity, fees, and reply to families.",
    listCentre: "List a centre",
    centreName: "Centre name",
    licenceNo: "Licence number",
    createListing: "Publish listing",
    spotsInfant: "Infant spots",
    spotsToddler: "Toddler spots",
    spotsPreschool: "Preschool spots",
    saveChanges: "Save changes",
    analytics: "This week",
    views: "Profile views",
    inquiries: "Inquiries",
    conversion: "Requests",
    roleParent: "Parent",
    roleProvider: "Provider",
    switchRole: "Using as",
    footerCopy: "KidEase is a Winnipeg-based, Canada-wide project serving families across the country.",
    pipeda: "PIPEDA & child safety",
    pipedaBody:
      "KidEase is built around PIPEDA’s consent, limiting-collection, and safeguarding principles. We store the minimum needed to run search, enrolment, and payments: your account, child care profiles you add (allergies, routines, emergency contacts), messages you send, and payment records. We do not sell personal information. Children’s details are visible only to you and to a centre you contact or book. Video check-in is a parent-initiated room — we do not offer continuous livestreams of children. Card payments, when enabled, run through Stripe. Messages are encrypted in transit (HTTPS).",
    aiUnavailable: "Matching is unavailable in this environment.",
    loading: "Loading",
    emptyMap: "Move the map or widen the radius.",
    openNow: "Open now",
    full: "Full",
    deposit: "First-month deposit",
    statusRequested: "Request sent",
    statusWaitlist: "Waitlist",
    statusAccepted: "Spot offered",
    statusActive: "Spot confirmed",
    statusCancelled: "Cancelled",
    statusDeclined: "Declined",
    heroCta: "Search Daycares Near Me",
    heroSub: "See monthly fees, open spots, and reviews before you tour.",
    findSpotsNear: "Find available spots near you.",
    heroTrust: "Built for Canadian families • Licensed facilities only • Real location photos",
    trustLicensedOnly: "Licensed",
    trustLiveAvail: "Storefront photos",
    trustGoogle: "Search near you",
    trustSecure: "Private",
    bookConfidenceTitle: "Book with confidence",
    bookConfidenceBody:
      "Every daycare on KidEase is provincially licensed. Live listings show real-time availability and pricing, so you know exactly what you’re requesting. Read Google reviews and message centres directly — all in one place.",
    liveMeans: "Live = actively managing availability on KidEase",
    licensedCentreLine: "This is a licensed childcare centre.",
    liveListingLine: "Live listing — availability and pricing updated by the provider.",
    viewOnGoogle: "View on Google",
    allCentresLicensed: "All centres are provincially licensed",
    stripeSecure: "Secure payments powered by Stripe",
    realGoogleReviews: "Real reviews from Google",
    youStayInControl: "You stay in control of every enrolment",
    providerDiscover: "Get discovered by parents who are already looking for care in your area — while keeping full control.",
    providerApproveT: "You approve every request",
    providerApprove: "Nothing happens without your say.",
    providerFreeT: "Free to claim your listing",
    providerFree: "Get started in minutes.",
    providerIntentT: "Parents come with real intent",
    providerIntent: "They can see your availability and pricing upfront.",
    providerRatesT: "Your rates, your rules",
    providerRates: "You set pricing and open spots.",
    providerSecureT: "Secure and professional",
    providerSecure: "Messaging and payments handled safely in one place.",
    providerTrustBody:
      "KidEase helps licensed daycares fill empty spots without giving up control. Parents search by location, see your live availability, and send requests directly to you. You decide who to accept. Claiming your listing is free and takes just a few minutes.",
    claimCtaSupport: "Claim your free listing today and start appearing as a Live daycare in front of local parents.",
    orEnterCity: "Or enter city or postal code",
    changeLocation: "Change location",
    providerLogin: "Daycare Sign In",
    popular: "Try",
    guestBrowse: "Browse without an account. Sign in when you want to book.",
    noReviews: "No parent reviews in-app yet. Hours and vacancies come from the provincial or territorial registry.",
    getApp: "Get the app",
    getAppKicker: "iPhone, iPad, Android, and Mac",
    getAppLead: "The Canada-wide directory on your home screen. GPS search, licensed centres, and enrolment in your pocket.",
    installThisDevice: "Install on this phone",
    installIosHint: "Tap Share, then Add to Home Screen. KidEase opens full-screen like any App Store app.",
    installAndroidHint: "Add KidEase to your home screen. It runs full-screen, with GPS and payments.",
    installMacHint: "In Safari: File → Add to Dock. KidEase opens like any Mac app — no App Store wait.",
    addToDock: "Add to Dock on this Mac",
    xcodeTitle: "Open in Xcode on this Mac",
    xcodeBody: "Download the iOS project, double-click App.xcodeproj, pick your Apple ID team, and press Play. Product → Archive ships it to App Store Connect. A free Apple ID runs it on your iPhone; the paid Developer Program ($99/year) is required to list it.",
    downloadXcode: "Download Xcode project",
    installed: "Already on this device",
    appStore: "App Store",
    googlePlay: "Google Play",
    storeReady: "Ready for App Store and Google Play",
    storeReadyBody:
      "Native iOS and Android shells, store listings, privacy labels, and in-app account deletion are in this build. Publishing uses your Apple Developer Program and Google Play Console accounts. Until the listings go live, install from this page — same app, full screen.",
    featGps: "True GPS radius",
    featGpsBody: "Search licensed centres within the kilometres you set — from the phone’s location or a postal code.",
    featCentres: "Canada-wide directory",
    featCentresBody: "Licensed centres in every province and territory. Each listing uses a storefront photo of the building when one can be verified.",
    featPay: "Deposits in-app",
    featPayBody: "Cards, Apple Pay, Google Pay, PayPal, and Interac. Childcare is a real-world service, not a digital IAP.",
    featSafe: "Built for PIPEDA",
    featSafeBody: "Child profiles stay with you and the centre you contact. Delete your account any time.",
    onYourPhone: "On the phone",
    onYourPhoneLead: "KidEase on iPhone — home, map search, a listing, and sign in.",
    terms: "Terms",
    cookies: "Cookies",
    support: "Support",
    supportLead: "Parents and providers — we read every note. Apple and Google review also uses this page as the support URL.",
    supportSent: "Message sent. We’ll reply by email.",
    deleteAccount: "Delete my account",
    deleteAccountLead: "Removes your children, messages, bookings, payments, and saved centres. This cannot be undone.",
    deleteAccountConfirm: "Delete everything",
    accountDeleted: "Account deleted",
    privacyNutrition: "What the stores ask us to disclose",
    locData: "Location — to search nearby centres. Not shared with other parents.",
    contactData: "Contact info — email and name from sign-in.",
    userContent: "User content — messages, enrolment notes, child first name and birthdate (only you and the centre).",
    identifiers: "Identifiers — account id for sign-in.",
    payData: "Payment records — deposit amount and method. Card numbers are never stored here.",
    featuredNear: "Open this month near",
    provinces: "Provinces",
    nearYou: "Near you",
    regionHint: "The app opens to your region. Allow location, or pick a province.",
    centresLabel: "licensed centres",
    usingLocation: "Using your location",
    requestSpotTitle: "Request a spot",
    requestSpotLead: "A few details about your child. The centre replies in chat.",
    childFullName: "Child’s full name",
    desiredStart: "Desired start date",
    specificDays: "Specific days",
    optionalMessage: "Message (optional)",
    messagePh: "Tell them a bit about your child or any questions…",
    sendRequest: "Send request",
    cancel: "Cancel",
    requestSentTitle: "Request sent successfully",
    requestSentBody: "The daycare has been notified. You can now chat with them.",
    goToConversation: "Go to conversation",
    statusUnderReview: "Under review",
    statusOffered: "Spot offered",
    myRequests: "My requests",
    directions: "Directions",
    dayMon: "Mon",
    dayTue: "Tue",
    dayWed: "Wed",
    dayThu: "Thu",
    dayFri: "Fri",
    incomingRequests: "Incoming requests",
    markReview: "Under review",
    offerSpot: "Offer spot",
    waitlistChild: "Waitlist",
    declineRequest: "Decline",
    openChat: "Open chat",
    requestNote: "Parent message",
    onMap: "On the map",
    openGoogleMaps: "Open in Google Maps",
    requestSummary: "Spot request",
    noRequests: "No spot requests yet.",
    parentLabel: "Parent",
    notifyCentre: "The centre was notified by push, email, and in-app.",
    callSmsVideo: "Call, text, or video",
    viewRespond: "View Request & Respond",
    emailToCentre: "Email to the centre",
    childProfileTitle: "Child care profile",
    childProfileLead:
      "Allergies, food, and how they like to spend the day. The centre only sees this after you request a spot.",
    childIdentity: "Who they are",
    preferredName: "Preferred name / nickname",
    homeLanguage: "Language at home",
    homeLanguagePh: "English, French, Spanish…",
    childHealth: "Health & safety",
    allergies: "Allergies",
    allergiesPh: "Peanuts, dairy, bee stings… Write none if there are no known allergies.",
    epiPen: "Carries an EpiPen / auto-injector",
    epiPenBadge: "EpiPen",
    medicalNotes: "Medical conditions or extra care",
    medications: "Medications during care hours",
    doctorName: "Doctor or clinic",
    doctorPhone: "Clinic phone",
    childFood: "Food",
    foodsLike: "Foods they like",
    foodsLikePh: "Pasta, apples, yogurt…",
    foodsAvoid: "Foods they will not eat",
    foodsAvoidPh: "Texture, taste, or family rule",
    diet: "Diet",
    dietPh: "Halal, vegetarian, lactose-free…",
    childComfort: "Comfort & routine",
    likes: "Things they like to do",
    likesPh: "Blocks, outdoor play, music, stories…",
    comfortItem: "Comfort item",
    comfortItemPh: "Blanket, stuffy, soother…",
    napRoutine: "Nap / sleep routine",
    napRoutinePh: "Sleeps after lunch, needs a story, white noise…",
    toilet: "Toileting",
    toiletUnknown: "Not sure yet",
    toiletDiapers: "Diapers",
    toiletTraining: "Potty training",
    toiletIndependent: "Independent",
    soothes: "How they calm down",
    soothesPh: "A lap, a song, a quiet corner…",
    fears: "Fears or things to avoid",
    fearsPh: "Loud rooms, dogs, being left at the door…",
    childPickup: "Emergency & pickup",
    emergencyName: "Emergency contact name",
    emergencyPhone: "Emergency phone",
    pickupPeople: "People allowed to pick up",
    pickupPeoplePh: "Full names. The centre will ask for ID.",
    childPerms: "Permissions",
    photoOk: "Photos of my child at the centre are OK",
    sunscreenOk: "Staff may apply sunscreen",
    extraNotes: "Anything else educators should know",
    saveProfile: "Save profile",
    editChild: "Edit profile",
    newChild: "Add another child",
    profileSaved: "Child profile saved",
    sharedWithCentre: "Shared with the centre after you request a spot",
    childCareCard: "Child care card",
    noAllergies: "No allergies listed",
    pickChild: "Use a saved child",
    newChildOption: "New child",
    completeProfile: "Complete their care profile",
    noneListed: "Not listed",
    yes: "Yes",
    no: "No",
    howStressFree: "Here’s how KidEase works",
    featuredBody:
      "Every listing shows a real photo of the location so you know exactly what the place looks like. Only licensed facilities are included.",
    viewDetails: "View Details",
    kmAway: "km away",
    bandWalk: "walkable",
    bandNearby: "nearby",
    bandCommute: "short drive",
    bandDrive: "drive",
    servesArea: "Serves your area",
    filterCatchment: "Serves my area",
    trustWhyTitle: "Why Parents Trust KidEase",
    trustWhy1: "We only list provincially licensed daycares across Canada.",
    trustWhy2: "Every listing features a real photo of the actual storefront so you can recognize the location.",
    trustWhy3: "Information is kept clear and transparent — no hidden fees or confusing details.",
    trustWhy4: "Your searches stay private. We do not sell your data.",
    trustWhyLocal:
      "A Canada-wide directory so parents can find licensed care near them — safely, clearly, and with confidence.",
    quotesTitle: "What Parents Are Saying",
    quote1: "Finally a simple way to see what’s actually close to home. The real photos made a big difference.",
    quote1By: "Canadian parent",
    quote2: "I liked that it only shows licensed places. Made the whole search feel less overwhelming.",
    quote2By: "Local mom",
    quote3: "Clear info and actual pictures of the buildings. Exactly what I needed.",
    quote3By: "Parent of a toddler",
    finalCtaTitle: "Ready when you are.",
    finalCtaBody: "Parents looking for care, or licensed centres ready to go live — enroll here.",
    howItWorksCta: "How It Works",
    verifyListings: "How we verify listings",
    mbChildcare: "Manitoba Child Care",
    neverSell: "We respect your privacy. Your data is never sold.",
    aboutTitle: "About KidEase",
    aboutHero:
      "KidEase is a Canada-wide app that helps parents find licensed daycare near them — quickly, clearly, and with confidence.",
    aboutIntro:
      "We created KidEase because searching for childcare can feel overwhelming. Parents need reliable information, real photos of the actual locations, and a simple way to see what’s closest to home or work. That’s exactly what we set out to deliver.",
    aboutMissionT: "Our Mission",
    aboutMission:
      "To make finding quality, licensed daycare across Canada easier and less stressful for families.",
    aboutDifferentT: "What Makes KidEase Different",
    aboutDiff1: "We only list provincially licensed daycares",
    aboutDiff2: "Every listing features a real storefront photo so you can recognize the location",
    aboutDiff3: "Search is built around proximity — see what’s actually near you",
    aboutDiff4: "Information is kept clear and transparent",
    aboutLocalT: "Built for Canadian families",
    aboutLocal1:
      "KidEase is a Canada-wide project, started in Winnipeg by people who know how hard it is to find licensed care. The directory covers licensed daycares in every province and territory.",
    aboutLocal2:
      "Our focus is simple: give parents better tools and clearer information so they can make confident decisions for their children.",
    aboutCommitT: "Our Commitment",
    aboutCommit1: "Accuracy and transparency",
    aboutCommit2: "Only licensed facilities",
    aboutCommit3: "Real photos of real locations",
    aboutCommit4: "A clean, easy-to-use experience",
    aboutCommit5: "Respect for your privacy",
    aboutClose: "KidEase is here to support Canadian families in one of the most important decisions they make.",
    team: "Meet the Team",
    teamIntro:
      "KidEase was founded in Winnipeg by two entrepreneurs who wanted a simpler, safer way for Canadian families to find licensed daycare — anywhere in the country.",
    kyleRole: "Co-Founder",
    kyleBio1:
      "Kyle is a Winnipeg-based business operator with extensive experience in local operations, customer service, and building practical tools that solve real problems for families and businesses in Manitoba.",
    kyleBio2:
      "As Co-Founder of KidEase, Kyle focuses on making sure the platform stays practical, accurate, and genuinely useful for parents searching for licensed care close to home — anywhere in Canada.",
    kevinRole: "Co-Founder",
    kevinBio1: "Kevin brings strong leadership and operational experience from the Winnipeg business community.",
    kevinBio2:
      "As Co-Founder, Kevin helps guide the direction of KidEase with a focus on reliability, Canada-wide coverage, and creating a platform parents can trust.",
    teamGoalT: "Our Shared Goal",
    teamGoal:
      "Together, Kyle and Kevin built KidEase as a Canada-wide, trustworthy tool for finding licensed daycare — with real information, real photos, and real proximity.",
    contact: "Contact",
    contactTitle: "Contact Us",
    contactIntro: "Have a question, suggestion, or need help using KidEase? We’d love to hear from you.",
    daycareEnrollLead: "If you are a daycare, secure your spot.",
    enrollNow: "Enroll Now",
    enrollFormTitle: "Tell us about your daycare",
    enrollFormLead: "We’ll email you to help claim your listing. Goes to kyle@kidease.ca.",
    enrollCentre: "Daycare name",
    enrollManual: "Enter name manually",
    enrollManualHint: "Not in the list? Choose this and type your centre name.",
    enrollPickHint: "Start typing — we’ll match licensed centres. Manual stays at the top.",
    listingContact: "Contact",
    listingContactLead: "Ask about openings or details at {name}. We’ll reply from kyle@kidease.ca.",
    listingContactSent: "Message sent. We’ll get back to you by email.",
    helpBot: "KidEase Help",
    liveChat: "Live Chat",
    helpBotLead: "Ask about licensed care, benefits, or your listing.",
    helpBotHello: "Hi — I’m the KidEase helper. Ask about finding a centre, $10-a-day, or claiming a listing.",
    helpBotPh: "Ask a question…",
    helpBotTyping: "Typing…",
    helpBotFail: "Couldn’t send that. Email kyle@kidease.ca.",
    helpBotAgent: "Talk to a live agent",
    close: "Close",
    enrollCity: "City / province",
    enrollPhone: "Phone",
    enrollMessage: "Message",
    enrollMessagePh: "Hours, ages you serve, licence number, or anything we should know…",
    enrollSent: "Request sent. We’ll email you within 1–2 business days.",
    partnerPerksTitle: "Why centres partner with KidEase",
    perkParents: "Access to parents across Canada who are actively looking for care",
    perkBrand: "More brand exposure for your business",
    perkPage: "A free website landing page for your centre",
    perkSpots: "Help filling open spots and capturing future bookings",
    perkChat: "In-app communication with parents",
    perkNear: "Proximity locating so nearby families find you first",
    perkMobile: "Everything managed from a mobile app",
    perkPay: "Payments processed in the app and paid to you directly, quickly",
    perkGrow: "A simple way to grow your enrolment",
    contactSubject: "Subject",
    subjectGeneral: "General Question",
    subjectListing: "Listing Feedback",
    subjectTech: "Technical Issue",
    subjectPartner: "Partnership",
    subjectOther: "Other",
    helloEmail: "kyle@kidease.ca",
    contactDirect: "Direct contact",
    contactResponse: "We typically respond within 1–2 business days.",
    contactLocation:
      "KidEase is a Winnipeg-based project, built to serve families across Canada.",
    contactPrivacy: "Your message is private. We do not share or sell your contact information.",
    contactSent: "Thanks — we received your message and will reply within 1–2 business days.",
    messageLabel: "Message",
    submit: "Submit",
    licenseActive: "Licence active",
    licenseStatus: "Status",
    licenceRecord: "Licence & inspections",
    licenceRecordLead:
      "This centre is on a provincial or territorial registry. KidEase does not replace the official record — open it to see inspections, complaints, and any corrections.",
    lastInspection: "Inspections",
    seeOfficialRecord: "See the official record",
    viewLicenceRecord: "View official licence record",
    viewLicenceShort: "Licence Record",
    checkSubsidy: "Check subsidy / $10-a-day",
    badgeTenAsk: "$10-a-day",
    badgeTen: "$10-a-day",
    badgeFifteen: "$15-a-day",
    badgeReducedQc: "Reduced-contribution (QC)",
    badgeSubsidy: "Subsidy-eligible (licensed)",
    availUnknown: "Availability unknown",
    availUnknownLead: "This centre hasn’t confirmed open spots on KidEase. Call or book a tour to confirm.",
    feeUnknown: "Fee not confirmed",
    feeUnknownLead: "Monthly fees are confirmed after the centre claims this listing. Ask about $10-a-day or subsidy when you tour.",
    aidOnListing: "Fee reduction and subsidy are applied by the province, not by KidEase.",
    cwelccAskNote: "Some licensed centres participate in $10-a-day / reduced parent fees. Confirm with the centre — it is not automatic everywhere.",
    cwelccQcNote: "Quebec reduced-contribution spaces are a separate system from the tax credit. Ask if this is a subsidized (CPE / reduced) space.",
    bookTour: "Book a tour",
    tourLead: "Pick a date to walk through the centre. This is not an enrolment request.",
    tourDefaultNote: "I’d like to tour the centre.",
    requestSentTitleTour: "Tour requested",
    requestSentBodyTour: "The centre will see your visit request in their inbox. You can add details in the chat.",
    compare: "Compare",
    comparing: "In compare",
    compareNow: "Compare selected",
    addToCompare: "Add to compare",
    clearCompare: "Clear",
    compareTitle: "Compare centres",
    compareEmpty: "Select up to 3 listings from search to compare hours, fees, spots, and ratings.",
    filterOpen: "Open now",
    filterWaitlist: "Waitlist",
    filterUnknown: "Unknown availability",
    filterTen: "$10-a-day / reduced fee",
    filterMeals: "Meals",
    filterOutdoor: "Outdoor space",
    filterInclusive: "Inclusion",
    filterFrench: "French",
    filterExtended: "Extended hours",
    filterInfant: "Infant program",
    spotsUpdated: "Spots last updated",
    tourChecklist: "Tour checklist",
    tourChecklistLead: "Take this list when you visit. Confirm licence, ratios, and how they handle allergies before you enrol.",
    tourQ1: "Is the provincial licence posted, and can I see the last inspection?",
    tourQ2: "What are staff-to-child ratios in the room my child would join?",
    tourQ3: "How do you handle allergies, medication, and nap time?",
    tourQ4: "How much outdoor time is there, in all weather?",
    tourQ5: "Do you participate in $10-a-day / reduced fees, and do you accept subsidy?",
    tourQ6: "How do pickup authorization and visitors work at the door?",
    interiorPhotoNote: "Add 3–5 interior photos (playroom, yard, cubbies) before parents will trust a Live listing. Storefront alone is not enough.",
    interiors: "Interior photos",
    rolePickTitle: "Enrol Now",
    rolePickLead: "Choose your role to get started on KidEase.",
    roleParentTitle: "Parent / Guardian",
    roleParentBody: "Search licensed daycares, see fees and open spots, request tours.",
    roleParentCta: "Continue as parent",
    roleDaycareTitle: "Daycare / Centre",
    roleDaycareBody: "Claim your listing, post open spots, receive parent inquiries.",
    roleDaycareCta: "Continue as daycare",
    parentContactTitle: "Find care for your family",
    parentContactIntro:
      "Tell us what you’re looking for — city, ages, and when you need a spot. We’ll reply from kyle@kidease.ca within 1–2 business days.",
    subjectCare: "Finding care",
    enrollBothLead: "Parents and licensed centres can enroll here.",
  },
  fr: {
    app: "KidEase",
    tagline: "Trouvez une garderie permise près de chez vous — simplement et en toute confiance",
    search: "Rechercher",
    explore: "Explorer",
    benefitsTab: "Programme d’aide à la garde d’enfants",
    benefitsShort: "Programme d’aide à la garde d’enfants",
    benefitsTitle: "Aide pour payer la garde",
    benefitsLead:
      "La plupart des tarifs réduits du programme pancanadien d’apprentissage et de garde des jeunes enfants s’appliquent automatiquement dans les garderies participantes. Une aide supplémentaire pour les familles à plus faible revenu (subvention) se demande à part, et elle change selon la province.",
    benefitsApply: "Présenter une demande sur le site officiel",
    benefitsBcT: "Colombie-Britannique",
    benefitsBc: "Prestation pour la garde d’enfants abordable — via My Family Services.",
    benefitsMbT: "Manitoba",
    benefitsMb: "Subvention pour les familles admissibles utilisant un service permis.",
    benefitsAbT: "Alberta",
    benefitsAb: "Subvention pour les enfants d’âge scolaire + subvention d’abordabilité / tarifs 15 $ par jour pour les plus jeunes.",
    benefitsOnT: "Ontario",
    benefitsOn: "La subvention est gérée localement. Trouvez votre CMSM ou DSSAB.",
    benefitsQcT: "Québec",
    benefitsQc: "Places à contribution réduite et crédit d’impôt via Revenu Québec.",
    benefitsFedT: "Allocation canadienne pour enfants",
    benefitsFed: "Paiement fédéral mensuel pour les familles admissibles.",
    benefitsSkT: "Saskatchewan",
    benefitsSk:
      "Garde réglementée à 10 $ par jour pour les enfants de moins de 6 ans. Les familles à faible revenu peuvent aussi obtenir de l’aide via le Saskatchewan Employment Incentive.",
    benefitsNsT: "Nouvelle-Écosse",
    benefitsNs: "Frais parentaux réduits + programme de subvention pour les familles admissibles.",
    benefitsNbT: "Nouveau-Brunswick",
    benefitsNb: "Programme de subvention parentale et programme d’aide à la garde pour les familles admissibles.",
    benefitsPeT: "Île-du-Prince-Édouard",
    benefitsPe: "Garde réglementée à 10 $ par jour + programme de subvention.",
    benefitsNlT: "Terre-Neuve-et-Labrador",
    benefitsNl: "Garde réglementée à 10 $ par jour + programme de subvention.",
    benefitsYtT: "Yukon",
    benefitsYt: "Programme universel (environ 10 $ par jour) + subvention pour la garde d’enfants.",
    benefitsNtT: "Territoires du Nord-Ouest",
    benefitsNt: "Subvention à la réduction des frais (environ 10 $ par jour) + aide possible au revenu.",
    benefitsNuT: "Nunavut",
    benefitsNu: "Garde réglementée à 10 $ par jour + subvention pour les familles admissibles.",
    benefitsNote: "KidEase ne traite pas ces demandes. Les sites officiels s’ouvrent dans un nouvel onglet.",
    saved: "Favoris",
    enrolled: "Inscriptions",
    messages: "Messages",
    profile: "Profil",
    inbox: "Messages",
    account: "Compte",
    provider: "Fournisseur",
    signIn: "Connexion",
    signOut: "Déconnexion",
    continueGoogle: "Continuer avec Google",
    continueX: "Continuer avec X",
    continueApple: "Connexion avec Apple",
    orEmail: "ou utilisez le courriel",
    email: "Courriel",
    password: "Mot de passe",
    name: "Nom",
    createAccount: "Créer un compte",
    haveAccount: "Déjà un compte? Connexion",
    needAccount: "Besoin d'un compte? Créez-en un",
    loginLead: "Enregistrez des centres, demandez une place et écrivez aux éducatrices.",
    loginLeadParent: "Créez votre compte parent pour chercher, enregistrer des centres et demander une place.",
    loginLeadProvider: "Créez votre compte fournisseur pour réclamer votre fiche et gérer les places et les tarifs.",
    roleHeadline: "Trouvez la garderie idéale près de chez vous",
    roleLead: "Choisissez comment vous utiliserez KidEase. Vous pourrez changer plus tard dans votre compte.",
    imParent: "Je suis un parent",
    imProvider: "Je suis un fournisseur de garde",
    alreadyAccount: "Vous avez déjà un compte ?",
    logIn: "Connexion",
    parentSignIn: "Connexion parent",
    providerSignIn: "Connexion fournisseur",
    useLocation: "Ma position",
    locating: "Localisation…",
    presenceLive: "Position en direct",
    presenceFresh: "Position à jour",
    presenceStale: "Dernière position connue",
    liveInArea: "{n} actifs sur KidEase dans ce secteur",
    locationPh: "Adresse, ville ou code postal",
    radius: "Rayon",
    km: "km",
    mi: "mi",
    unitsKm: "km",
    unitsMi: "mi",
    distanceUnit: "Distance",
    miAway: "mi",
    locationConsentTitle: "Afficher les garderies permises près de vous",
    locationConsentBody:
      "KidEase utilise votre position précise seulement pendant la recherche. Nous ne demandons jamais la position en arrière-plan.",
    locationConsentAllow: "Utiliser la position précise",
    locationConsentLater: "Pas maintenant",
    locationWhileUsing: "Position précise pendant l’utilisation",
    map: "Carte",
    mapRoad: "Carte",
    mapSat: "Satellite",
    list: "Liste",
    sort: "Trier",
    filters: "Filtres",
    sortDistance: "Distance",
    sortPrice: "Prix",
    sortRating: "Note",
    sortOpen: "Places ouvertes",
    anyAge: "Tout âge",
    infant: "Nourrisson",
    toddler: "Tout-petit",
    preschool: "Préscolaire",
    schoolAge: "Âge scolaire",
    agesUnknown: "Âges non confirmés",
    agesAccepted: "Âges acceptés",
    agesShort: "Âges",
    agesLead: "Cela s’affiche sur votre fiche publique. Indiquez les mois (ex. 12 à 60).",
    ageMin: "Plus jeune (mois)",
    ageMax: "Plus âgé (mois)",
    monthlyFrom: "à partir de",
    month: "/mois",
    spots: "places ouvertes",
    spotsAvailable: "Places disponibles",
    waitlist: "Liste d'attente",
    licensed: "Permis",
    live: "En ligne",
    liveBadge: "Actif sur KidEase",
    notOnKidEase: "Pas encore sur KidEase",
    liveOnly: "Fiches actives",
    showAll: "Toutes les fiches",
    unclaimedNotice: "Cette garderie n’a pas encore rejoint KidEase. Vous pouvez tout de même consulter les renseignements de base.",
    unclaimedLead: "Les renseignements ci-dessous proviennent des registres publics. Les tarifs et les places peuvent ne pas être à jour.",
    requestUnavailable: "Vous pourrez demander une place lorsque ce centre sera actif.",
    noLiveResults: "Aucun centre actif dans ce rayon. Affichez toutes les fiches, ou élargissez la recherche.",
    reviews: "avis",
    googleReviews: "Google",
    readGoogleReviews: "Lire les avis Google",
    noResults: "Aucun centre dans ce rayon. Élargissez le cercle ou changez de ville.",
    featured: "Garderies permises près de chez vous",
    recentlyViewed: "Consultées récemment",
    availableNow: "Garderies disponibles",
    availableNextMonth: "D’autres centres près de vous",
    how: "Comment ça fonctionne",
    how1t: "Cherchez par lieu",
    how1: "Entrez une adresse, une ville ou un code postal, ou utilisez votre position. Les résultats se trient par distance — km ou milles dans les filtres.",
    how2t: "Voyez de vrais détails",
    how2: "Photos de la devanture, âges acceptés, heures et infos clés, en un coup d’œil.",
    how3t: "Contactez en toute confiance",
    how3: "Écrivez directement aux centres qui conviennent à votre famille.",
    bilingual: "Anglais et français",
    language: "Langue",
    claimTitle: "Réclamez votre garderie",
    claimLead: "Trouvez la fiche déjà tirée des registres publics et de Google, puis confirmez que vous la dirigez. Pas de doublon.",
    claimSearchPh: "Nom, adresse ou numéro de permis",
    claimThis: "Réclamer cette fiche",
    alreadyClaimed: "Déjà réclamée",
    claimEmpty: "Commencez à taper un nom, une adresse ou une ville — les résultats apparaissent en direct.",
    claimNoMatch: "Aucun centre correspondant. Vérifiez l’orthographe, ou inscrivez un nouveau centre ci-dessous.",
    claimMissing: "Vous ne trouvez pas votre centre ?",
    verifyListing: "Vérifier cette fiche",
    verifyLead: "Confirmez que vous gérez",
    claimCodeSent: "Votre code de réclamation (aussi envoyé par courriel / texto)",
    claimCodeHint: "Entrez le code envoyé par courriel (et par texto si nous avons un numéro).",
    claimCode: "Code de réclamation",
    licensePhoto: "Photo du permis de garde",
    finishClaim: "Vérifier et prendre en charge",
    claimVerified: "Fiche réclamée. Vous pouvez mettre à jour les places, les tarifs et les photos.",
    claimOwned: "Cette fiche est déjà sur votre compte.",
    claimFailed: "Impossible de réclamer cette fiche.",
    photoTooBig: "Choisissez une photo de moins de 1,5 Mo.",
    storefrontPhoto: "Photo de la façade",
    storefrontLead:
      "Ajoutez une photo claire de l’entrée pour que les parents reconnaissent le bâtiment. Elle remplace la vue de rue sur votre fiche.",
    storefrontHint: "Façade, porte ou enseigne — bien éclairée. JPG ou PNG de moins de 1,5 Mo.",
    storefrontCta: "Téléverser la photo de façade",
    promoteTitle: "Mettre en avant cette fiche",
    promoteLead:
      "Payez pour apparaître en haut des résultats près de chez vous. Les fiches prioritaire affichent un badge bleu lumineux pour attirer l’œil des parents.",
    promoteWeek: "7 jours",
    promoteMonth: "30 jours",
    promoteQuarter: "90 jours",
    promotePay: "Mettre en avant",
    promoteExtend: "Prolonger la priorité",
    promoteActive: "Mise en avant active jusqu’au",
    promoteSecure: "Paiement par carte sécurisé. La visibilité prioritaire commence tout de suite.",
    priority: "Prioritaire",
    contactEmail: "Courriel d’affaires",
    businessDetails: "Coordonnées",
    claimCta: "Réclamez votre garderie",
    claimCtaLead: "Si vous dirigez un centre déjà sur KidEase, réclamez la fiche et indiquez vos places et tarifs mensuels.",
    isThisYours: "C’est votre centre ?",
    claimedBadge: "Réclamée",
    pendingClaim: "Vérification en cours",
    uploadNew: "Remplacer la photo",
    phoneLabel: "Téléphone",
    cityLabel: "Ville",
    provinceLabel: "Province",
    postalLabel: "Code postal",
    addressLabel: "Adresse",
    privacyNote: "Conçu pour les familles canadiennes. Nous ne vendons pas les données des enfants.",
    privacy: "Confidentialité",
    viewListing: "Voir la fiche",
    book: "Demander une place",
    message: "Message",
    save: "Enregistrer",
    savedDone: "Enregistré",
    call: "Appeler",
    video: "Visio",
    hours: "Heures",
    ages: "Âges acceptés",
    months: "mois",
    license: "Permis",
    pricing: "Frais mensuels des parents",
    infantFee: "Nourrisson",
    toddlerFee: "Tout-petit",
    preschoolFee: "Préscolaire",
    partTime: "Temps partiel",
    fullTime: "Temps plein",
    availability: "Places par mois",
    about: "À propos",
    amenities: "Ce qu'ils offrent",
    parentReviews: "Avis de parents",
    similar: "Aussi à proximité",
    back: "Retour",
    startMonth: "Mois de début",
    schedule: "Horaire",
    child: "Enfant",
    addChild: "Ajouter un enfant",
    childName: "Prénom de l'enfant",
    birthdate: "Date de naissance",
    notes: "Notes pour le personnel",
    submitRequest: "Envoyer la demande",
    needSignIn: "Connectez-vous pour demander une place.",
    requestSent: "Demande envoyée",
    requestWait: "Ajouté à la liste d'attente",
    dashboard: "Votre famille",
    bookings: "Mes demandes",
    payments: "Paiements",
    children: "Enfants",
    noBookings: "Aucune demande pour l'instant.",
    noPayments: "Aucun paiement pour l'instant.",
    noPaymentsLead: "Les paiements apparaissent après qu’un centre vous offre une place. Rien n’est facturé avant.",
    noChildren: "Ajoutez un enfant pour accélérer les demandes.",
    noChildrenLead: "Un court profil (prénom, date de naissance, allergies) accompagne chaque demande.",
    noSaved: "Aucun centre enregistré pour l’instant.",
    noSavedLead: "Enregistrez une fiche depuis la recherche, puis demandez une place ou envoyez un profil.",
    noInbox: "Aucun message pour l’instant.",
    noInboxLead: "Une conversation s’ouvre quand vous demandez une place ou qu’un centre répond.",
    deskHome: "Accueil",
    deskHomeTitle: "Votre espace famille",
    deskHomeLead: "Cherchez une place permise, rouvrez vos centres, suivez les demandes et écrivez aux éducateurs — au même endroit.",
    deskHomeSearch: "Trouvez des garderies permises près de chez vous.",
    deskHomeSaved: "Les centres que vous voulez revoir.",
    deskHomeBookings: "Demandes et offres de place.",
    deskHomeInbox: "Messages avec les centres contactés.",
    emptyFindCare: "Trouver une place",
    emptyAddChild: "Ajouter un enfant",
    emptyClaimCentre: "Réclamer un centre",
    emptyListCentre: "Ajouter un centre",
    comparePickMore: " — choisissez-en un autre",
    compareCount: "Comparaison de {n} centres",
    mailSendFailed: "Envoi impossible. Écrivez à kyle@kidease.ca.",
    checkInConsent: "La caméra et le micro restent sur cet appareil. Démarrez seulement quand vous êtes prêt.",
    checkInStart: "Démarrer la caméra",
    checkInPreview: "Aperçu seulement — ce n’est pas encore un appel en direct avec le centre.",
    verifyHowTitle: "Comment nous vérifions les fiches",
    verifyHow1: "Chaque fiche publique vient d’un registre provincial ou territorial de garde permise. La garde non permise n’est pas listée.",
    verifyHow2: "Le fournisseur réclame la page existante, téléverse le permis actuel, puis attend la revue KidEase. Nous approuvons, demandons plus d’info, ou refusons — avec une note visible.",
    verifyHow3: "Les fiches En ligne montrent les tarifs et places saisis par le fournisseur. Les pages non réclamées montrent seulement les données du registre, jamais un prix inventé.",
    verifyHow4: "Les fiches de test et laboratoires QA sont cachées de la recherche, de la carte et des URL publiques. Si une fiche semble fausse, écrivez à kyle@kidease.ca.",
    faqTitle: "Foire aux questions",
    faqLead: "Réponses courtes pour les parents et les garderies permises. Une personne? Écrivez à kyle@kidease.ca.",
    faqQ1: "Faut-il un compte pour chercher?",
    faqA1: "Non. Les visiteurs peuvent chercher sur la carte, ouvrir une fiche, comparer et envoyer une note. Connectez-vous pour enregistrer, demander une place ou écrire à un centre En ligne.",
    faqQ2: "Comment utilisez-vous ma position?",
    faqA2: "Seulement pendant la recherche, et seulement si vous l’autorisez. Nous ne demandons jamais la position en arrière-plan. Vous pouvez toujours entrer une adresse, une ville ou un code postal.",
    faqQ3: "Que veut dire En ligne?",
    faqA3: "Le centre a réclamé la fiche et KidEase l’a approuvée. Tarifs et places viennent du fournisseur. Les pages non réclamées restent permises — les détails peuvent dater.",
    faqQ4: "Comment réclamer ma garderie?",
    faqA4: "Ouvrez Réclamer votre garderie, trouvez la fiche existante, entrez le code envoyé, et téléversez le permis provincial actuel. Nous revoyons chaque demande.",
    pendingHonesty: "Les totaux en attente ne sont pas encaissés.",
    requestInfo: "Demander de l’info",
    lastReviewed: "Revue",
    activityAll: "Toute l’activité",
    locationPrivacyLink: "Comment nous utilisons la position",
    pay: "Payer maintenant",
    payTitle: "Sécurisez la place",
    payLead: "Le paiement n’est disponible qu’après l’approbation de la garderie. Vous verrez le montant exact avant de confirmer.",
    payFor: "Frais mensuels du premier mois",
    payWhat: "Ce que vous payez",
    paySecureNote: "Traité de façon sécurisée. Cartes, Apple Pay et Google Pay.",
    stripeMark: "Paiements sécurisés avec Stripe",
    receiptTitle: "Reçu de paiement",
    receiptLead: "Une copie est enregistrée dans votre compte et envoyée à la garderie.",
    viewReceipt: "Voir le reçu",
    awaitingPay: "En attente du paiement du parent",
    paymentReceived: "Paiement reçu",
    notApprovedPay: "Le paiement s’ouvre une fois que la garderie vous offre une place.",
    printReceipt: "Imprimer le reçu",
    paidTo: "Payé à",
    receiptNo: "Reçu",
    amount: "Montant",
    method: "Mode",
    card: "Crédit ou débit",
    apple: "Apple Pay",
    google: "Google Pay",
    paypal: "PayPal",
    interac: "Virement Interac",
    payNow: "Confirmer le paiement",
    paid: "Payé",
    pending: "En attente",
    cardNumber: "Numéro de carte",
    expiry: "Expiration",
    cvc: "CVC",
    interacHint: "Nous affichons une référence à envoyer de votre banque. Ici, le paiement passe d'en attente à payé.",
    writeMessage: "Écrire un message",
    send: "Envoyer",
    sms: "Texto",
    voice: "Voix",
    videoCall: "Vidéo",
    checkInTitle: "Salle de visio",
    checkInLead: "Une salle privée avec le centre. Votre caméra reste sur cet appareil. Le flux du centre est la vue d'ensemble qu'il a publiée — jamais une caméra cachée sur un enfant.",
    mute: "Muet",
    camera: "Caméra",
    end: "Terminer",
    match: "Demander à Grok",
    matchPh: "ex. nourrisson, bilingue, 10 $ par jour, près de Saint-Boniface",
    matchGo: "Trouver des correspondances",
    matchNeed: "Décrivez le service dont vous avez besoin",
    providerTitle: "Votre centre",
    providerLead: "Mettez à jour les places, les tarifs et répondez aux familles.",
    listCentre: "Inscrire un centre",
    centreName: "Nom du centre",
    licenceNo: "Numéro de permis",
    createListing: "Publier la fiche",
    spotsInfant: "Places nourrissons",
    spotsToddler: "Places tout-petits",
    spotsPreschool: "Places préscolaires",
    saveChanges: "Enregistrer",
    analytics: "Cette semaine",
    views: "Vues du profil",
    inquiries: "Messages",
    conversion: "Demandes",
    roleParent: "Parent",
    roleProvider: "Fournisseur",
    switchRole: "Espace",
    footerCopy: "KidEase est un projet basé à Winnipeg, au service des familles partout au Canada.",
    pipeda: "PIPEDA et sécurité des enfants",
    pipedaBody:
      "KidEase s'appuie sur le consentement, la limitation de la collecte et les mesures de protection de la LPRPDE. Nous conservons le minimum pour la recherche, l'inscription et les paiements. Nous ne vendons pas de renseignements personnels. Les détails sur les enfants ne sont visibles que par vous et par un centre que vous contactez. La visio est lancée par le parent — pas de diffusion continue d'enfants. Les paiements par carte, lorsqu'ils sont activés, passent par Stripe. Les messages sont chiffrés en transit (HTTPS).",
    aiUnavailable: "La correspondance n'est pas disponible ici.",
    loading: "Chargement",
    emptyMap: "Déplacez la carte ou élargissez le rayon.",
    openNow: "Ouvert",
    full: "Complet",
    deposit: "Dépôt du premier mois",
    statusRequested: "Demande envoyée",
    statusWaitlist: "Liste d'attente",
    statusAccepted: "Place offerte",
    statusActive: "Place confirmée",
    statusCancelled: "Annulée",
    statusDeclined: "Refusée",
    heroCta: "Chercher des garderies près de moi",
    heroSub: "Uniquement des établissements permis par la province. De vraies photos de la devanture. Des infos claires pour choisir en confiance.",
    findSpotsNear: "Trouvez des places disponibles près de chez vous.",
    heroTrust: "Conçu pour les familles canadiennes • Établissements permis seulement • Photos réelles des lieux",
    trustLicensedOnly: "Permis seulement",
    trustLiveAvail: "Vraies photos de devanture",
    trustGoogle: "Recherche près de vous",
    trustSecure: "Infos claires et transparentes",
    bookConfidenceTitle: "Réservez en toute confiance",
    bookConfidenceBody:
      "Chaque garderie sur KidEase est permise par la province. Les fiches actives affichent les places et les tarifs en temps réel, pour que vous sachiez exactement ce que vous demandez. Lisez les avis Google et écrivez aux centres — au même endroit.",
    liveMeans: "En ligne = le centre gère ses places sur KidEase",
    licensedCentreLine: "Ceci est un service de garde permis.",
    liveListingLine: "Fiche active — places et tarifs mis à jour par le fournisseur.",
    viewOnGoogle: "Voir sur Google",
    allCentresLicensed: "Tous les centres sont permis par la province",
    stripeSecure: "Paiements sécurisés avec Stripe",
    realGoogleReviews: "Vrais avis Google",
    youStayInControl: "Vous gardez le contrôle de chaque inscription",
    providerDiscover: "Soyez vu par des parents qui cherchent déjà une place dans votre secteur — tout en gardant le contrôle.",
    providerApproveT: "Vous approuvez chaque demande",
    providerApprove: "Rien n’avance sans votre accord.",
    providerFreeT: "Réclamation gratuite",
    providerFree: "Commencez en quelques minutes.",
    providerIntentT: "Des parents vraiment intéressés",
    providerIntent: "Ils voient vos places et vos tarifs avant d’écrire.",
    providerRatesT: "Vos tarifs, vos règles",
    providerRates: "Vous fixez les prix et les places ouvertes.",
    providerSecureT: "Sécurisé et professionnel",
    providerSecure: "Messages et paiements au même endroit, en toute sécurité.",
    providerTrustBody:
      "KidEase aide les garderies permises à remplir les places libres sans céder le contrôle. Les parents cherchent par lieu, voient votre disponibilité et vous envoient des demandes. Vous décidez qui accepter. Réclamer votre fiche est gratuit et prend quelques minutes.",
    claimCtaSupport: "Réclamez votre fiche gratuite et apparaissez comme garderie En ligne auprès des parents du quartier.",
    orEnterCity: "Ou entrez une ville ou un code postal",
    changeLocation: "Changer de lieu",
    providerLogin: "Connexion garderie",
    popular: "Essayer",
    guestBrowse: "Parcourez sans compte. Connectez-vous pour réserver.",
    noReviews: "Pas encore d’avis de parents ici. Heures et places viennent du registre provincial ou territorial.",
    getApp: "Télécharger l’appli",
    getAppKicker: "iPhone, iPad, Android et Mac",
    getAppLead: "Le répertoire pancanadien sur l’écran d’accueil. Recherche GPS, centres permis et inscription dans votre poche.",
    installThisDevice: "Installer sur ce téléphone",
    installIosHint: "Touchez Partager, puis Sur l’écran d’accueil. KidEase s’ouvre en plein écran, comme une appli de l’App Store.",
    installAndroidHint: "Ajoutez KidEase à l’écran d’accueil. Plein écran, GPS et paiements.",
    installMacHint: "Dans Safari : Fichier → Ajouter au Dock. KidEase s’ouvre comme n’importe quelle appli Mac.",
    addToDock: "Ajouter au Dock sur ce Mac",
    xcodeTitle: "Ouvrir dans Xcode sur ce Mac",
    xcodeBody: "Téléchargez le projet iOS, double-cliquez App.xcodeproj, choisissez votre équipe Apple ID, puis lecture. Product → Archive l’envoie à App Store Connect. Un Apple ID gratuit le lance sur votre iPhone; le programme développeur (99 $/an) est requis pour le publier.",
    downloadXcode: "Télécharger le projet Xcode",
    installed: "Déjà sur cet appareil",
    appStore: "App Store",
    googlePlay: "Google Play",
    storeReady: "Prêt pour l’App Store et Google Play",
    storeReadyBody:
      "Les coques iOS et Android, les fiches des boutiques, les étiquettes de confidentialité et la suppression du compte sont dans cette version. La publication passe par vos comptes Apple Developer et Google Play Console. En attendant, installez depuis cette page — la même appli, en plein écran.",
    featGps: "Rayon GPS réel",
    featGpsBody: "Cherchez des centres permis dans les kilomètres que vous fixez — depuis la position du téléphone ou un code postal.",
    featCentres: "Répertoire pancanadien",
    featCentresBody: "Centres permis dans chaque province et territoire. Chaque fiche utilise une photo de la devanture lorsqu’elle peut être vérifiée.",
    featPay: "Dépôts dans l’appli",
    featPayBody: "Cartes, Apple Pay, Google Pay, PayPal et Interac. La garde est un service réel, pas un achat intégré numérique.",
    featSafe: "Conçu pour la LPRPDE",
    featSafeBody: "Les profils d’enfants restent entre vous et le centre contacté. Supprimez votre compte en tout temps.",
    onYourPhone: "Sur votre téléphone",
    onYourPhoneLead: "KidEase sur iPhone — accueil, carte, une fiche, et connexion.",
    terms: "Conditions",
    cookies: "Témoins",
    support: "Soutien",
    supportLead: "Parents et fournisseurs — nous lisons chaque note. Apple et Google utilisent aussi cette page comme URL de soutien.",
    supportSent: "Message envoyé. Nous répondrons par courriel.",
    deleteAccount: "Supprimer mon compte",
    deleteAccountLead: "Efface vos enfants, messages, demandes, paiements et centres enregistrés. Irréversible.",
    deleteAccountConfirm: "Tout supprimer",
    accountDeleted: "Compte supprimé",
    privacyNutrition: "Ce que les boutiques nous demandent de déclarer",
    locData: "Position — pour chercher des centres près de vous. Non partagée avec d’autres parents.",
    contactData: "Coordonnées — courriel et nom à la connexion.",
    userContent: "Contenu — messages, notes d’inscription, prénom et date de naissance de l’enfant (vous et le centre seulement).",
    identifiers: "Identifiants — identifiant de compte pour la connexion.",
    payData: "Paiements — montant et mode du dépôt. Aucun numéro de carte n’est conservé ici.",
    featuredNear: "Places ouvertes ce mois-ci près de",
    provinces: "Provinces",
    nearYou: "Près de vous",
    regionHint: "L’appli s’ouvre sur votre région. Autorisez la position, ou choisissez une province.",
    centresLabel: "centres permis",
    usingLocation: "Votre position",
    requestSpotTitle: "Demander une place",
    requestSpotLead: "Quelques précisions sur votre enfant. Le centre répond dans le clavardage.",
    childFullName: "Nom complet de l’enfant",
    desiredStart: "Date de début souhaitée",
    specificDays: "Jours précis",
    optionalMessage: "Message (facultatif)",
    messagePh: "Parlez-leur un peu de votre enfant ou posez une question…",
    sendRequest: "Envoyer la demande",
    cancel: "Annuler",
    requestSentTitle: "Demande envoyée",
    requestSentBody: "Le service de garde a été avisé. Vous pouvez maintenant discuter avec eux.",
    goToConversation: "Aller à la conversation",
    statusUnderReview: "En révision",
    statusOffered: "Place offerte",
    myRequests: "Mes demandes",
    directions: "Itinéraire",
    dayMon: "Lun",
    dayTue: "Mar",
    dayWed: "Mer",
    dayThu: "Jeu",
    dayFri: "Ven",
    incomingRequests: "Demandes reçues",
    markReview: "En révision",
    offerSpot: "Offrir une place",
    waitlistChild: "Liste d’attente",
    declineRequest: "Refuser",
    openChat: "Ouvrir le clavardage",
    requestNote: "Message du parent",
    onMap: "Sur la carte",
    openGoogleMaps: "Ouvrir dans Google Maps",
    requestSummary: "Demande de place",
    noRequests: "Aucune demande pour l’instant.",
    parentLabel: "Parent",
    notifyCentre: "Le centre a été avisé par notification, courriel et dans l’appli.",
    callSmsVideo: "Appel, texto ou visio",
    viewRespond: "Voir la demande et répondre",
    emailToCentre: "Courriel au centre",
    childProfileTitle: "Profil de l’enfant",
    childProfileLead:
      "Allergies, nourriture et habitudes. Le centre ne voit ces détails qu’après une demande de place.",
    childIdentity: "Identité",
    preferredName: "Prénom usuel / surnom",
    homeLanguage: "Langue à la maison",
    homeLanguagePh: "Français, anglais, espagnol…",
    childHealth: "Santé et sécurité",
    allergies: "Allergies",
    allergiesPh: "Arachides, lait, piqûres d’abeille… Indiquez aucune s’il n’y en a pas.",
    epiPen: "Porte un EpiPen / auto-injecteur",
    epiPenBadge: "EpiPen",
    medicalNotes: "Conditions médicales ou soins particuliers",
    medications: "Médicaments pendant les heures de garde",
    doctorName: "Médecin ou clinique",
    doctorPhone: "Téléphone de la clinique",
    childFood: "Alimentation",
    foodsLike: "Aliments préférés",
    foodsLikePh: "Pâtes, pommes, yogourt…",
    foodsAvoid: "Aliments à éviter",
    foodsAvoidPh: "Texture, goût ou règle familiale",
    diet: "Régime",
    dietPh: "Halal, végétarien, sans lactose…",
    childComfort: "Confort et routine",
    likes: "Activités préférées",
    likesPh: "Blocs, jeux dehors, musique, histoires…",
    comfortItem: "Objet réconfort",
    comfortItemPh: "Couverture, toutou, suce…",
    napRoutine: "Sieste / sommeil",
    napRoutinePh: "Dort après le dîner, a besoin d’une histoire…",
    toilet: "Toilettes",
    toiletUnknown: "Pas encore certain",
    toiletDiapers: "Couches",
    toiletTraining: "Apprentissage de la propreté",
    toiletIndependent: "Autonome",
    soothes: "Comment se calmer",
    soothesPh: "Sur les genoux, une chanson, un coin calme…",
    fears: "Peurs ou choses à éviter",
    fearsPh: "Bruit, chiens, séparation à la porte…",
    childPickup: "Urgence et ramassage",
    emergencyName: "Nom du contact d’urgence",
    emergencyPhone: "Téléphone d’urgence",
    pickupPeople: "Personnes autorisées à venir chercher l’enfant",
    pickupPeoplePh: "Noms complets. Le centre demandera une pièce d’identité.",
    childPerms: "Autorisations",
    photoOk: "Les photos de mon enfant au centre sont permises",
    sunscreenOk: "Le personnel peut appliquer de l’écran solaire",
    extraNotes: "Tout autre détail pour les éducatrices",
    saveProfile: "Enregistrer le profil",
    editChild: "Modifier le profil",
    newChild: "Ajouter un autre enfant",
    profileSaved: "Profil enregistré",
    sharedWithCentre: "Partagé avec le centre après une demande de place",
    childCareCard: "Fiche de l’enfant",
    noAllergies: "Aucune allergie indiquée",
    pickChild: "Enfant déjà enregistré",
    newChildOption: "Nouvel enfant",
    completeProfile: "Compléter le profil de soins",
    noneListed: "Non indiqué",
    yes: "Oui",
    no: "Non",
    howStressFree: "Trouver une place ne devrait pas être stressant. Voici comment KidEase fonctionne :",
    featuredBody:
      "Chaque fiche montre une vraie photo du lieu pour que vous sachiez à quoi ressemble l’endroit. Seuls les établissements permis sont inclus.",
    viewDetails: "Voir les détails",
    kmAway: "km",
    bandWalk: "à pied",
    bandNearby: "à proximité",
    bandCommute: "court trajet",
    bandDrive: "en voiture",
    servesArea: "Sert votre secteur",
    filterCatchment: "Sert mon secteur",
    trustWhyTitle: "Pourquoi les parents font confiance à KidEase",
    trustWhy1: "Nous n’inscrivons que des garderies permises par la province, partout au Canada.",
    trustWhy2: "Chaque fiche présente une vraie photo de la devanture pour que vous reconnaissiez le lieu.",
    trustWhy3: "Les informations restent claires et transparentes — pas de frais cachés ni de détails confus.",
    trustWhy4: "Vos recherches restent privées. Nous ne vendons pas vos données.",
    trustWhyLocal:
      "Un répertoire pancanadien pour que les parents trouvent une garde permise près de chez eux — en toute sécurité, clairement et en confiance.",
    quotesTitle: "Ce que disent les parents",
    quote1: "Enfin une façon simple de voir ce qui est vraiment proche de la maison. Les vraies photos ont tout changé.",
    quote1By: "Parent canadien",
    quote2: "J’ai aimé que ça n’affiche que des places permises. La recherche est devenue beaucoup moins lourde.",
    quote2By: "Maman d’ici",
    quote3: "Des infos claires et de vraies photos des bâtiments. Exactement ce qu’il me fallait.",
    quote3By: "Parent d’un tout-petit",
    finalCtaTitle: "Prêt à trouver une place près de chez vous ?",
    finalCtaBody: "Parents à la recherche d’une place, ou garderies permises prêtes à passer en ligne — inscrivez-vous ici.",
    howItWorksCta: "Comment ça fonctionne",
    verifyListings: "Comment nous vérifions les fiches",
    mbChildcare: "Garde d’enfants au Manitoba",
    neverSell: "Nous respectons votre vie privée. Vos données ne sont jamais vendues.",
    aboutTitle: "À propos de KidEase",
    aboutHero:
      "KidEase est une appli pancanadienne qui aide les parents à trouver une garderie permise près de chez eux — rapidement, clairement et en confiance.",
    aboutIntro:
      "Nous avons créé KidEase parce que chercher une place en garde peut sembler lourd. Les parents ont besoin d’infos fiables, de vraies photos des lieux et d’un moyen simple de voir ce qui est proche de la maison ou du travail. C’est exactement ce que nous voulions offrir.",
    aboutMissionT: "Notre mission",
    aboutMission:
      "Rendre plus simple et moins stressante la recherche d’une garderie permise de qualité partout au Canada.",
    aboutDifferentT: "Ce qui distingue KidEase",
    aboutDiff1: "Nous n’inscrivons que des garderies permises par la province",
    aboutDiff2: "Chaque fiche montre une vraie photo de la devanture pour reconnaître le lieu",
    aboutDiff3: "La recherche est basée sur la proximité — voyez ce qui est vraiment près de vous",
    aboutDiff4: "Les informations restent claires et transparentes",
    aboutLocalT: "Conçu pour les familles canadiennes",
    aboutLocal1:
      "KidEase est un projet pancanadien, lancé à Winnipeg par des gens qui savent combien il est difficile de trouver une place permise. Le répertoire couvre les garderies permises de chaque province et territoire.",
    aboutLocal2:
      "Notre objectif est simple : de meilleurs outils et des infos plus claires pour que les parents décident en confiance pour leurs enfants.",
    aboutCommitT: "Notre engagement",
    aboutCommit1: "Exactitude et transparence",
    aboutCommit2: "Uniquement des établissements permis",
    aboutCommit3: "De vraies photos de vrais lieux",
    aboutCommit4: "Une expérience simple et claire",
    aboutCommit5: "Le respect de votre vie privée",
    aboutClose: "KidEase est là pour accompagner les familles canadiennes dans l’une des décisions les plus importantes.",
    team: "L’équipe",
    teamIntro:
      "KidEase a été fondée à Winnipeg par deux entrepreneurs qui voulaient un moyen plus simple et plus sûr pour les familles canadiennes de trouver une garderie permise — partout au pays.",
    kyleRole: "Cofondateur",
    kyleBio1:
      "Kyle est un entrepreneur de Winnipeg, avec une vaste expérience des opérations locales, du service à la clientèle et d’outils pratiques qui règlent de vrais problèmes pour les familles et les entreprises au Manitoba.",
    kyleBio2:
      "Comme cofondateur de KidEase, Kyle veille à ce que la plateforme reste pratique, exacte et vraiment utile pour les parents qui cherchent une place permise près de chez eux — partout au Canada.",
    kevinRole: "Cofondateur",
    kevinBio1: "Kevin apporte une solide expérience de leadership et d’opérations dans le milieu des affaires de Winnipeg.",
    kevinBio2:
      "Comme cofondateur, Kevin oriente KidEase vers la fiabilité, la couverture pancanadienne et une plateforme en laquelle les parents peuvent avoir confiance.",
    teamGoalT: "Notre objectif commun",
    teamGoal:
      "Ensemble, Kyle et Kevin ont créé KidEase : un outil pancanadien, clair et digne de confiance pour trouver une garderie permise — avec de vraies infos, de vraies photos et une vraie proximité.",
    contact: "Contact",
    contactTitle: "Nous joindre",
    contactIntro: "Une question, une suggestion, ou besoin d’aide avec KidEase ? Écrivez-nous.",
    daycareEnrollLead: "Si vous êtes une garderie, réservez votre place.",
    enrollNow: "S’inscrire maintenant",
    enrollFormTitle: "Parlez-nous de votre garderie",
    enrollFormLead: "Nous vous écrirons pour réclamer votre fiche. Envoi à kyle@kidease.ca.",
    enrollCentre: "Nom de la garderie",
    enrollManual: "Saisir le nom manuellement",
    enrollManualHint: "Pas dans la liste ? Choisissez ceci et tapez le nom.",
    enrollPickHint: "Commencez à taper — nous trouvons les centres permis. Manuel reste en haut.",
    listingContact: "Contacter",
    listingContactLead: "Demandez les places ou les détails pour {name}. Réponse de kyle@kidease.ca.",
    listingContactSent: "Message envoyé. Nous vous écrirons par courriel.",
    helpBot: "Aide KidEase",
    liveChat: "Clavardage en direct",
    helpBotLead: "Questions sur la garde permise, les prestations ou votre fiche.",
    helpBotHello: "Bonjour — je suis l’assistant KidEase. Cherchez un centre, le 10 $ par jour, ou réclamez une fiche.",
    helpBotPh: "Posez une question…",
    helpBotTyping: "Rédaction…",
    helpBotFail: "Envoi impossible. Écrivez à kyle@kidease.ca.",
    helpBotAgent: "Parler à un agent",
    close: "Fermer",
    enrollCity: "Ville / province",
    enrollPhone: "Téléphone",
    enrollMessage: "Message",
    enrollMessagePh: "Heures, âges, numéro de permis, ou tout autre détail…",
    enrollSent: "Demande envoyée. Nous vous écrirons sous 1 à 2 jours ouvrables.",
    partnerPerksTitle: "Pourquoi les garderies s’associent à KidEase",
    perkParents: "Accès à des parents partout au Canada qui cherchent activement une place",
    perkBrand: "Plus de visibilité pour votre établissement",
    perkPage: "Une page web gratuite pour votre centre",
    perkSpots: "Aide à remplir les places libres et à réserver l’avenir",
    perkChat: "Messagerie dans l’application avec les parents",
    perkNear: "Repérage par proximité pour que les familles du quartier vous trouvent en premier",
    perkMobile: "Tout se gère depuis l’application mobile",
    perkPay: "Paiements dans l’application, versés directement et rapidement",
    perkGrow: "Une façon simple d’augmenter vos inscriptions",
    contactSubject: "Sujet",
    subjectGeneral: "Question générale",
    subjectListing: "Commentaire sur une fiche",
    subjectTech: "Problème technique",
    subjectPartner: "Partenariat",
    subjectOther: "Autre",
    helloEmail: "kyle@kidease.ca",
    contactDirect: "Contact direct",
    contactResponse: "Nous répondons généralement en 1 ou 2 jours ouvrables.",
    contactLocation:
      "KidEase est un projet basé à Winnipeg, conçu pour servir les familles partout au Canada.",
    contactPrivacy: "Votre message est privé. Nous ne partageons ni ne vendons vos coordonnées.",
    contactSent: "Merci — nous avons reçu votre message et répondrons en 1 ou 2 jours ouvrables.",
    messageLabel: "Message",
    submit: "Envoyer",
    licenseActive: "Permis actif",
    licenseStatus: "Statut",
    licenceRecord: "Permis et inspections",
    licenceRecordLead:
      "Ce centre est au registre provincial ou territorial. KidEase ne remplace pas le dossier officiel — ouvrez-le pour voir les inspections, les plaintes et les corrections.",
    lastInspection: "Inspections",
    seeOfficialRecord: "Voir le dossier officiel",
    viewLicenceRecord: "Voir le dossier de permis",
    viewLicenceShort: "Dossier de permis",
    checkSubsidy: "Vérifier subvention / 10 $ par jour",
    badgeTenAsk: "10 $ par jour",
    badgeTen: "10 $ par jour",
    badgeFifteen: "15 $ par jour",
    badgeReducedQc: "Contribution réduite (QC)",
    badgeSubsidy: "Admissible à la subvention (permis)",
    availUnknown: "Disponibilité inconnue",
    availUnknownLead: "Ce centre n’a pas confirmé ses places sur KidEase. Appelez ou réservez une visite.",
    feeUnknown: "Tarif non confirmé",
    feeUnknownLead: "Les tarifs mensuels sont confirmés après que le centre réclame la fiche. Demandez le 10 $ par jour ou la subvention lors de la visite.",
    aidOnListing: "La réduction de tarifs et la subvention viennent de la province, pas de KidEase.",
    cwelccAskNote: "Certains centres permis participent au 10 $ par jour / tarifs réduits. Confirmez auprès du centre — ce n’est pas automatique partout.",
    cwelccQcNote: "Les places à contribution réduite au Québec sont distinctes du crédit d’impôt. Demandez s’il s’agit d’une place subventionnée (CPE).",
    bookTour: "Réserver une visite",
    tourLead: "Choisissez une date pour visiter. Ce n’est pas une demande d’inscription.",
    tourDefaultNote: "Je souhaite visiter le centre.",
    requestSentTitleTour: "Visite demandée",
    requestSentBodyTour: "Le centre verra votre demande de visite. Vous pouvez ajouter des détails dans le clavardage.",
    compare: "Comparer",
    comparing: "En comparaison",
    compareNow: "Comparer la sélection",
    addToCompare: "Ajouter à la comparaison",
    clearCompare: "Effacer",
    compareTitle: "Comparer les centres",
    compareEmpty: "Choisissez jusqu’à 3 fiches pour comparer heures, tarifs, places et notes.",
    filterOpen: "Places ouvertes",
    filterWaitlist: "Liste d’attente",
    filterUnknown: "Disponibilité inconnue",
    filterTen: "10 $ par jour / tarif réduit",
    filterMeals: "Repas",
    filterOutdoor: "Extérieur",
    filterInclusive: "Inclusion",
    filterFrench: "Français",
    filterExtended: "Heures prolongées",
    filterInfant: "Nourrissons",
    spotsUpdated: "Places mises à jour",
    tourChecklist: "Liste pour la visite",
    tourChecklistLead: "Apportez cette liste. Confirmez le permis, les ratios et les allergies avant d’inscrire.",
    tourQ1: "Le permis provincial est-il affiché, et puis-je voir la dernière inspection ?",
    tourQ2: "Quels sont les ratios dans le groupe de mon enfant ?",
    tourQ3: "Comment gérez-vous les allergies, les médicaments et la sieste ?",
    tourQ4: "Combien de temps dehors, par tous les temps ?",
    tourQ5: "Participez-vous au 10 $ par jour / tarifs réduits, et acceptez-vous la subvention ?",
    tourQ6: "Comment fonctionne l’autorisation au ramassage et les visiteurs à la porte ?",
    interiorPhotoNote: "Ajoutez 3 à 5 photos intérieures (salle de jeu, cour, casiers) avant de passer En ligne. La devanture seule ne suffit pas.",
    interiors: "Photos intérieures",
    rolePickTitle: "S’inscrire maintenant",
    rolePickLead: "Choisissez votre rôle pour commencer sur KidEase.",
    roleParentTitle: "Parent / Tuteur",
    roleParentBody: "Cherchez des garderies permises, voyez les tarifs et les places, demandez une visite.",
    roleParentCta: "Continuer comme parent",
    roleDaycareTitle: "Garderie / Centre",
    roleDaycareBody: "Réclamez votre fiche, publiez les places libres, recevez les demandes des parents.",
    roleDaycareCta: "Continuer comme garderie",
    parentContactTitle: "Trouver une place pour votre famille",
    parentContactIntro:
      "Dites-nous ce que vous cherchez — ville, âges et moment. Nous répondrons de kyle@kidease.ca sous 1 à 2 jours ouvrables.",
    subjectCare: "Recherche d’une place",
    enrollBothLead: "Les parents et les garderies permises peuvent s’inscrire ici.",
  },
} as const;

export type CopyKey = keyof typeof copy.en;

export function tx(locale: Locale, key: CopyKey): string {
  if (locale === "fr") return copy.fr[key];
  if (locale === "en") return copy.en[key];
  const extra = extraCopy[locale]?.[key];
  return extra ?? copy.en[key];
}
