import type { CopyKey } from "./copy";
import type { Locale } from "./types";

type Pack = Partial<Record<CopyKey, string>>;

const zh: Pack = {
  language: "语言",
  roleHeadline: "找到附近最合适的托儿所",
  imParent: "我是家长",
  imProvider: "我是托儿机构",
  alreadyAccount: "已有账户？",
  logIn: "登录",
  tagline: "持证托儿，离家更近。",
  search: "搜索",
  explore: "发现",
  saved: "收藏",
  inbox: "消息",
  account: "账户",
  provider: "机构",
  signIn: "登录",
  signOut: "退出",
  continueGoogle: "使用 Google 登录",
  continueX: "使用 X 登录",
  continueApple: "通过 Apple 登录",
  orEmail: "或使用电子邮箱",
  email: "电子邮箱",
  password: "密码",
  name: "姓名",
  createAccount: "创建账户",
  haveAccount: "已有账户？登录",
  needAccount: "需要账户？创建一个",
  loginLead: "收藏机构、申请学位并与老师沟通。",
  useLocation: "使用我的位置",
  locationPh: "城市或邮政编码",
  radius: "范围",
  km: "公里",
  map: "地图",
  list: "列表",
  sort: "排序",
  sortDistance: "距离",
  sortPrice: "价格",
  sortRating: "评分",
  sortOpen: "空位",
  anyAge: "不限年龄",
  infant: "婴儿",
  toddler: "幼儿",
  preschool: "学前",
  monthlyFrom: "起",
  month: "/月",
  spots: "个空位",
  waitlist: "候补",
  licensed: "持证",
  reviews: "条评价",
  noResults: "此范围内没有持证机构。扩大范围或换个城市试试。",
  featured: "本月您附近有空位",
  how: "如何使用",
  how1t: "设定范围",
  how1: "从家、公司或邮政编码搜索。距离以公里计。",
  how2t: "持证托儿机构",
  how2: "查看每月托儿费用、空位和评价，再选择最合适的机构。",
  how3t: "申请并付款",
  how3: "发送学位申请，与机构聊天，获录用后支付订金。",
  privacyNote: "为加拿大家庭而建。我们不出售儿童数据。",
  privacy: "隐私",
  cookies: "Cookie",
  viewListing: "查看详情",
  book: "申请学位",
  message: "发消息",
  save: "收藏",
  savedDone: "已收藏",
  call: "电话",
  video: "视频",
  hours: "开放时间",
  ages: "年龄",
  months: "个月",
  license: "许可证",
  pricing: "费用",
  infantFee: "婴儿月费",
  toddlerFee: "幼儿月费",
  preschoolFee: "学前月费",
  partTime: "兼职",
  fullTime: "全职",
  availability: "空位情况",
  about: "简介",
  amenities: "设施",
  parentReviews: "家长评价",
  similar: "附近类似机构",
  back: "返回",
  child: "孩子",
  addChild: "添加孩子",
  dashboard: "您的家庭",
  bookings: "我的申请",
  payments: "付款",
  children: "孩子",
  pay: "付款",
  loading: "加载中",
  heroCta: "搜索附近托儿",
  heroSub: "KidEase 会打开您所在的地区。用 GPS 或邮政编码按公里搜索全加拿大持证机构。",
  popular: "试试",
  guestBrowse: "无需账户即可浏览。申请学位时再登录。",
  getApp: "获取应用",
  provinces: "省份",
  nearYou: "靠近您",
  regionHint: "应用会打开您所在的地区。允许定位，或选择省份。",
  centresLabel: "所持证机构",
  usingLocation: "正在使用您的位置",
  requestSpotTitle: "申请学位",
  requestSpotLead: "填写孩子的基本信息。机构会在聊天中回复。",
  childFullName: "孩子全名",
  desiredStart: "希望入学日期",
  sendRequest: "发送申请",
  cancel: "取消",
  requestSentTitle: "申请已发送",
  goToConversation: "前往对话",
  myRequests: "我的申请",
  directions: "路线",
  childProfileTitle: "孩子照料档案",
  childProfileLead: "过敏、饮食和日常习惯。仅在您申请学位后机构才能看到。",
  allergies: "过敏",
  epiPen: "随身携带 EpiPen / 自动注射器",
  foodsLike: "喜欢的食物",
  likes: "喜欢做的事",
  saveProfile: "保存档案",
  editChild: "编辑档案",
  newChild: "再添加一个孩子",
  yes: "是",
  no: "否",
  statusRequested: "申请已发送",
  statusUnderReview: "审核中",
  statusOffered: "已提供学位",
  statusActive: "学位已确认",
  statusDeclined: "已拒绝",
  statusWaitlist: "候补名单",
  openChat: "打开聊天",
  completeProfile: "完善照料档案",
  childCareCard: "孩子照料卡",
  noAllergies: "未列出过敏",
  pickChild: "使用已保存的孩子",
  newChildOption: "新孩子",
  locating: "正在查找附近持证托儿…",
  featuredNear: "本月附近空位",
};

const yue: Pack = {
  language: "語言",
  tagline: "持牌託兒，離家更近。",
  search: "搜尋",
  explore: "探索",
  saved: "收藏",
  inbox: "訊息",
  account: "帳戶",
  provider: "機構",
  signIn: "登入",
  signOut: "登出",
  continueGoogle: "使用 Google 繼續",
  continueX: "使用 X 繼續",
  continueApple: "透過 Apple 登入",
  orEmail: "或使用電郵",
  email: "電郵",
  password: "密碼",
  name: "姓名",
  createAccount: "建立帳戶",
  haveAccount: "已有帳戶？登入",
  needAccount: "需要帳戶？建立一個",
  loginLead: "收藏中心、申請學位，同老師傾偈。",
  useLocation: "使用我嘅位置",
  locationPh: "城市或郵政編碼",
  radius: "範圍",
  km: "公里",
  map: "地圖",
  list: "列表",
  sort: "排序",
  sortDistance: "距離",
  sortPrice: "價格",
  sortRating: "評分",
  sortOpen: "空位",
  anyAge: "任何年齡",
  infant: "嬰兒",
  toddler: "幼兒",
  preschool: "學前",
  monthlyFrom: "起",
  month: "/月",
  spots: "個空位",
  waitlist: "輪候",
  licensed: "持牌",
  reviews: "則評價",
  noResults: "呢個範圍內冇持牌中心。試下擴大範圍或者換城市。",
  featured: "今個月附近有空位",
  how: "點樣用",
  how1t: "設定範圍",
  how1: "由屋企、公司或者郵政編碼搜尋。距離用公里。",
  how2t: "持牌幼兒中心",
  how2: "睇每月托兒費用、空位同評價，再揀最適合嘅。",
  how3t: "申請同付款",
  how3: "發送學位申請，同中心傾偈，有學位就俾訂金。",
  privacyNote: "為加拿大家庭而設。我哋唔會賣兒童資料。",
  privacy: "私隱",
  cookies: "Cookie",
  viewListing: "查看詳情",
  book: "申請學位",
  message: "訊息",
  save: "收藏",
  call: "電話",
  hours: "開放時間",
  pricing: "收費",
  child: "小朋友",
  addChild: "新增小朋友",
  dashboard: "你嘅家庭",
  children: "小朋友",
  pay: "付款",
  loading: "載入中",
  heroCta: "搜尋附近託兒",
  heroSub: "KidEase 會開啟你所在地區。用 GPS 或者郵政編碼，按公里搜尋全加拿大持牌中心。",
  popular: "試吓",
  guestBrowse: "唔使帳戶都可以瀏覽。申請學位先登入。",
  getApp: "下載應用程式",
  provinces: "省份",
  regionHint: "應用程式會開啟你所在地區。允許定位，或者揀省份。",
  centresLabel: "所持牌中心",
  requestSpotTitle: "申請學位",
  sendRequest: "發送申請",
  cancel: "取消",
  myRequests: "我嘅申請",
  directions: "路線",
  childProfileTitle: "小朋友照顧檔案",
  childProfileLead: "過敏、食物同日常習慣。你申請學位之後，中心先會睇到。",
  allergies: "過敏",
  saveProfile: "儲存檔案",
  yes: "係",
  no: "唔係",
  statusRequested: "已發送申請",
  statusOffered: "已提供學位",
  locating: "緊搵附近持牌託兒…",
};

const pa: Pack = {
  language: "ਭਾਸ਼ਾ",
  tagline: "ਲਾਇਸੰਸਸ਼ੁਦਾ ਦੇਖਭਾਲ, ਘਰ ਦੇ ਨੇੜੇ।",
  search: "ਖੋਜ",
  explore: "ਵੇਖੋ",
  saved: "ਸੰਭਾਲੇ",
  inbox: "ਸੁਨੇਹੇ",
  account: "ਖਾਤਾ",
  provider: "ਕੇਂਦਰ",
  signIn: "ਸਾਈਨ ਇਨ",
  signOut: "ਸਾਈਨ ਆਉਟ",
  continueGoogle: "Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
  continueX: "X ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
  continueApple: "Apple ਨਾਲ ਸਾਈਨ ਇਨ",
  orEmail: "ਜਾਂ ਈਮੇਲ ਵਰਤੋ",
  email: "ਈਮੇਲ",
  password: "ਪਾਸਵਰਡ",
  name: "ਨਾਮ",
  createAccount: "ਖਾਤਾ ਬਣਾਓ",
  haveAccount: "ਪਹਿਲਾਂ ਖਾਤਾ ਹੈ? ਸਾਈਨ ਇਨ",
  needAccount: "ਖਾਤਾ ਚਾਹੀਦਾ? ਬਣਾਓ",
  loginLead: "ਕੇਂਦਰ ਸੰਭਾਲੋ, ਸੀਟ ਲਈ ਬੇਨਤੀ ਕਰੋ, ਅਤੇ ਅਧਿਆਪਕਾਂ ਨਾਲ ਗੱਲ ਕਰੋ।",
  useLocation: "ਮੇਰੀ ਲੋਕੇਸ਼ਨ ਵਰਤੋ",
  locationPh: "ਸ਼ਹਿਰ ਜਾਂ ਪੋਸਟਲ ਕੋਡ",
  radius: "ਘੇਰਾ",
  km: "ਕਿਮੀ",
  map: "ਨਕਸ਼ਾ",
  list: "ਸੂਚੀ",
  sort: "ਕ੍ਰਮ",
  sortDistance: "ਦੂਰੀ",
  sortPrice: "ਕੀਮਤ",
  sortRating: "ਰੇਟਿੰਗ",
  sortOpen: "ਖਾਲੀ ਸੀਟਾਂ",
  anyAge: "ਕੋਈ ਵੀ ਉਮਰ",
  infant: "ਬੱਚਾ",
  toddler: "ਨਿਆਣਾ",
  preschool: "ਪ੍ਰੀ-ਸਕੂਲ",
  monthlyFrom: "ਤੋਂ",
  month: "/ਮਹੀਨਾ",
  spots: "ਸੀਟਾਂ ਖੁੱਲ੍ਹੀਆਂ",
  waitlist: "ਉਡੀਕ ਸੂਚੀ",
  licensed: "ਲਾਇਸੰਸਸ਼ੁਦਾ",
  reviews: "ਸਮੀਖਿਆਵਾਂ",
  noResults: "ਇਸ ਘੇਰੇ ਵਿੱਚ ਕੋਈ ਲਾਇਸੰਸਸ਼ੁਦਾ ਕੇਂਦਰ ਨਹੀਂ। ਘੇਰਾ ਵਧਾਓ ਜਾਂ ਹੋਰ ਸ਼ਹਿਰ ਅਜ਼ਮਾਓ।",
  featured: "ਇਸ ਮਹੀਨੇ ਤੁਹਾਡੇ ਨੇੜੇ ਖੁੱਲ੍ਹੀਆਂ",
  how: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
  how1t: "ਘੇਰਾ ਸੈੱਟ ਕਰੋ",
  how1: "ਘਰ, ਕੰਮ ਜਾਂ ਪੋਸਟਲ ਕੋਡ ਤੋਂ ਖੋਜੋ। ਦੂਰੀ ਕਿਲੋਮੀਟਰ ਵਿੱਚ ਹੈ।",
  how2t: "ਲਾਇਸੰਸਸ਼ੁਦਾ ਚਾਈਲਡਕੇਅਰ",
  how2: "ਮਹੀਨਾਵਾਰ ਖਰਚੇ, ਉਪਲਬਧਤਾ ਅਤੇ ਸਮੀਖਿਆਵਾਂ ਵੇਖੋ, ਫਿਰ ਸਭ ਤੋਂ ਵਧੀਆ ਚੁਣੋ।",
  how3t: "ਬੇਨਤੀ ਅਤੇ ਭੁਗਤਾਨ",
  how3: "ਸੀਟ ਲਈ ਬੇਨਤੀ ਭੇਜੋ, ਗੱਲ ਕਰੋ, ਫਿਰ ਜੇ ਸੀਟ ਮਿਲੇ ਤਾਂ ਡਿਪਾਜ਼ਿਟ ਦਿਓ।",
  privacyNote: "ਕੈਨੇਡੀਅਨ ਪਰਿਵਾਰਾਂ ਲਈ। ਅਸੀਂ ਬੱਚਿਆਂ ਦਾ ਡਾਟਾ ਨਹੀਂ ਵੇਚਦੇ।",
  privacy: "ਪਰਦੇਦਾਰੀ",
  cookies: "ਕੂਕੀਜ਼",
  viewListing: "ਵੇਰਵਾ ਵੇਖੋ",
  book: "ਸੀਟ ਲਈ ਬੇਨਤੀ",
  message: "ਸੁਨੇਹਾ",
  save: "ਸੰਭਾਲੋ",
  call: "ਕਾਲ",
  hours: "ਘੰਟੇ",
  pricing: "ਕੀਮਤ",
  child: "ਬੱਚਾ",
  addChild: "ਬੱਚਾ ਜੋੜੋ",
  dashboard: "ਤੁਹਾਡਾ ਪਰਿਵਾਰ",
  children: "ਬੱਚੇ",
  pay: "ਭੁਗਤਾਨ",
  loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ",
  heroCta: "ਨੇੜਲੀ ਦੇਖਭਾਲ ਖੋਜੋ",
  heroSub: "KidEase ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਖੁੱਲ੍ਹਦਾ ਹੈ। GPS ਜਾਂ ਪੋਸਟਲ ਕੋਡ ਨਾਲ ਕੈਨੇਡਾ ਭਰ ਦੇ ਲਾਇਸੰਸਸ਼ੁਦਾ ਕੇਂਦਰ ਕਿਲੋਮੀਟਰ ਵਿੱਚ ਖੋਜੋ।",
  popular: "ਅਜ਼ਮਾਓ",
  guestBrowse: "ਬਿਨਾਂ ਖਾਤੇ ਵੇਖੋ। ਸੀਟ ਲਈ ਬੇਨਤੀ ਵੇਲੇ ਸਾਈਨ ਇਨ ਕਰੋ।",
  getApp: "ਐਪ ਲਵੋ",
  provinces: "ਸੂਬੇ",
  regionHint: "ਐਪ ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਖੁੱਲ੍ਹਦੀ ਹੈ। ਲੋਕੇਸ਼ਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ, ਜਾਂ ਸੂਬਾ ਚੁਣੋ।",
  centresLabel: "ਲਾਇਸੰਸਸ਼ੁਦਾ ਕੇਂਦਰ",
  requestSpotTitle: "ਸੀਟ ਲਈ ਬੇਨਤੀ",
  sendRequest: "ਬੇਨਤੀ ਭੇਜੋ",
  cancel: "ਰੱਦ ਕਰੋ",
  myRequests: "ਮੇਰੀਆਂ ਬੇਨਤੀਆਂ",
  directions: "ਰਾਹ",
  childProfileTitle: "ਬੱਚੇ ਦੀ ਦੇਖਭਾਲ ਪ੍ਰੋਫਾਈਲ",
  childProfileLead: "ਐਲਰਜੀ, ਭੋਜਨ ਅਤੇ ਰੋਜ਼ਾਨਾ ਆਦਤਾਂ। ਕੇਂਦਰ ਇਹ ਤਾਂ ਹੀ ਵੇਖੇਗਾ ਜਦੋਂ ਤੁਸੀਂ ਸੀਟ ਲਈ ਬੇਨਤੀ ਕਰੋਗੇ।",
  allergies: "ਐਲਰਜੀਆਂ",
  saveProfile: "ਪ੍ਰੋਫਾਈਲ ਸੰਭਾਲੋ",
  yes: "ਹਾਂ",
  no: "ਨਹੀਂ",
  statusRequested: "ਬੇਨਤੀ ਭੇਜੀ ਗਈ",
  locating: "ਤੁਹਾਡੇ ਨੇੜੇ ਲਾਇਸੰਸਸ਼ੁਦਾ ਦੇਖਭਾਲ ਲੱਭ ਰਹੇ ਹਾਂ…",
};

const es: Pack = {
  language: "Idioma",
  tagline: "Cuidado con licencia, cerca de casa.",
  search: "Buscar",
  explore: "Explorar",
  saved: "Guardados",
  inbox: "Mensajes",
  account: "Cuenta",
  provider: "Centro",
  signIn: "Iniciar sesión",
  signOut: "Cerrar sesión",
  continueGoogle: "Continuar con Google",
  continueX: "Continuar con X",
  continueApple: "Iniciar sesión con Apple",
  orEmail: "o use el correo",
  email: "Correo",
  password: "Contraseña",
  name: "Nombre",
  createAccount: "Crear cuenta",
  haveAccount: "¿Ya tiene cuenta? Inicie sesión",
  needAccount: "¿Necesita una cuenta? Cree una",
  loginLead: "Guarde centros, solicite un cupo y hable con las educadoras.",
  useLocation: "Usar mi ubicación",
  locationPh: "Ciudad o código postal",
  radius: "Radio",
  km: "km",
  map: "Mapa",
  list: "Lista",
  sort: "Ordenar",
  sortDistance: "Distancia",
  sortPrice: "Precio",
  sortRating: "Calificación",
  sortOpen: "Cupos",
  anyAge: "Cualquier edad",
  infant: "Bebé",
  toddler: "Infante",
  preschool: "Preescolar",
  monthlyFrom: "desde",
  month: "/mes",
  spots: "cupos",
  waitlist: "lista de espera",
  licensed: "Con licencia",
  reviews: "reseñas",
  noResults: "No hay centros con licencia en este radio. Amplíe el círculo o pruebe otra ciudad.",
  featured: "Cupos este mes cerca de usted",
  how: "Cómo funciona",
  how1t: "Elija un radio",
  how1: "Busque desde casa, el trabajo o un código postal. Las distancias son en kilómetros.",
  how2t: "Guarderías autorizadas",
  how2: "Vea los costos mensuales, la disponibilidad y las reseñas antes de elegir la mejor.",
  how3t: "Solicite y pague",
  how3: "Envíe una solicitud, chatee con el centro y pague un depósito si le ofrecen el cupo.",
  privacyNote: "Hecho para familias en Canadá. No vendemos datos de menores.",
  privacy: "Privacidad",
  cookies: "Cookies",
  viewListing: "Ver ficha",
  book: "Solicitar cupo",
  message: "Mensaje",
  save: "Guardar",
  call: "Llamar",
  hours: "Horario",
  pricing: "Precios",
  child: "Niño/a",
  addChild: "Añadir un niño/a",
  dashboard: "Su familia",
  children: "Niños",
  pay: "Pagar",
  loading: "Cargando",
  heroCta: "Buscar cuidado cerca",
  heroSub: "KidEase se abre en su región. Busque centros con licencia por kilómetro con GPS o código postal, en todo Canadá.",
  popular: "Probar",
  guestBrowse: "Explore sin cuenta. Inicie sesión cuando quiera solicitar un cupo.",
  getApp: "Obtener la app",
  provinces: "Provincias",
  regionHint: "La app se abre en su región. Permita la ubicación o elija una provincia.",
  centresLabel: "centros con licencia",
  requestSpotTitle: "Solicitar un cupo",
  requestSpotLead: "Unos datos de su hijo/a. El centro responde en el chat.",
  childFullName: "Nombre completo del niño/a",
  desiredStart: "Fecha de inicio deseada",
  sendRequest: "Enviar solicitud",
  cancel: "Cancelar",
  requestSentTitle: "Solicitud enviada",
  goToConversation: "Ir a la conversación",
  myRequests: "Mis solicitudes",
  directions: "Cómo llegar",
  childProfileTitle: "Perfil de cuidado",
  childProfileLead: "Alergias, comida y rutina. El centro solo lo ve después de solicitar un cupo.",
  allergies: "Alergias",
  epiPen: "Lleva EpiPen / autoinyector",
  foodsLike: "Comidas que le gustan",
  likes: "Cosas que le gusta hacer",
  saveProfile: "Guardar perfil",
  editChild: "Editar perfil",
  newChild: "Añadir otro niño/a",
  yes: "Sí",
  no: "No",
  statusRequested: "Solicitud enviada",
  statusUnderReview: "En revisión",
  statusOffered: "Cupo ofrecido",
  statusActive: "Cupo confirmado",
  statusDeclined: "Rechazada",
  statusWaitlist: "Lista de espera",
  openChat: "Abrir chat",
  completeProfile: "Completar el perfil de cuidado",
  childCareCard: "Ficha del niño/a",
  noAllergies: "Sin alergias indicadas",
  pickChild: "Usar un niño/a guardado",
  newChildOption: "Niño/a nuevo",
  locating: "Buscando cuidado con licencia cerca de usted…",
  featuredNear: "Cupos este mes cerca de",
};

const ar: Pack = {
  language: "اللغة",
  tagline: "رعاية مرخّصة، قريبة من المنزل.",
  search: "بحث",
  explore: "استكشاف",
  saved: "المحفوظات",
  inbox: "الرسائل",
  account: "الحساب",
  provider: "المركز",
  signIn: "تسجيل الدخول",
  signOut: "تسجيل الخروج",
  continueGoogle: "المتابعة مع Google",
  continueX: "المتابعة مع X",
  continueApple: "تسجيل الدخول باستخدام Apple",
  orEmail: "أو استخدم البريد",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  name: "الاسم",
  createAccount: "إنشاء حساب",
  haveAccount: "لديك حساب؟ سجّل الدخول",
  needAccount: "تحتاج حساباً؟ أنشئ واحداً",
  loginLead: "احفظ المراكز واطلب مكاناً وتواصل مع المربيات.",
  useLocation: "استخدم موقعي",
  locationPh: "المدينة أو الرمز البريدي",
  radius: "النطاق",
  km: "كم",
  map: "الخريطة",
  list: "القائمة",
  sort: "ترتيب",
  sortDistance: "المسافة",
  sortPrice: "السعر",
  sortRating: "التقييم",
  sortOpen: "الأماكن المتاحة",
  anyAge: "أي عمر",
  infant: "رضيع",
  toddler: "طفل صغير",
  preschool: "ما قبل المدرسة",
  monthlyFrom: "من",
  month: "/شهر",
  spots: "أماكن متاحة",
  waitlist: "قائمة انتظار",
  licensed: "مرخّص",
  reviews: "تقييمات",
  noResults: "لا مراكز مرخّصة ضمن هذا النطاق. وسّع الدائرة أو جرّب مدينة أخرى.",
  featured: "أماكن متاحة هذا الشهر بالقرب منك",
  how: "كيف يعمل",
  how1t: "حدّد نطاقاً",
  how1: "ابحث من المنزل أو العمل أو الرمز البريدي. المسافات بالكيلومتر.",
  how2t: "مرافق رعاية مرخّصة",
  how2: "اطّلع على التكاليف الشهرية والتوفر والتقييمات قبل اختيار الأنسب.",
  how3t: "اطلب وادفع",
  how3: "أرسل طلب مكان، تحدث مع المركز، ثم ادفع العربون إذا عُرض المكان.",
  privacyNote: "مبني لعائلات كندا. لا نبيع بيانات الأطفال.",
  privacy: "الخصوصية",
  cookies: "ملفات تعريف الارتباط",
  viewListing: "عرض الصفحة",
  book: "طلب مكان",
  message: "رسالة",
  save: "حفظ",
  call: "اتصال",
  hours: "الساعات",
  pricing: "الأسعار",
  child: "الطفل",
  addChild: "إضافة طفل",
  dashboard: "عائلتك",
  children: "الأطفال",
  pay: "دفع",
  loading: "جارٍ التحميل",
  heroCta: "ابحث عن رعاية قريبة",
  heroSub: "يفتح KidEase على منطقتك. ابحث عن مراكز مرخّصة بالكيلومتر عبر GPS أو الرمز البريدي في كل كندا.",
  popular: "جرّب",
  guestBrowse: "تصفح بدون حساب. سجّل الدخول عند طلب مكان.",
  getApp: "حمّل التطبيق",
  provinces: "المقاطعات",
  regionHint: "يفتح التطبيق على منطقتك. اسمح بالموقع أو اختر مقاطعة.",
  centresLabel: "مركزاً مرخّصاً",
  requestSpotTitle: "طلب مكان",
  requestSpotLead: "بعض التفاصيل عن طفلك. يرد المركز في المحادثة.",
  childFullName: "الاسم الكامل للطفل",
  desiredStart: "تاريخ البدء المطلوب",
  sendRequest: "إرسال الطلب",
  cancel: "إلغاء",
  requestSentTitle: "تم إرسال الطلب",
  goToConversation: "الذهاب إلى المحادثة",
  myRequests: "طلباتي",
  directions: "الاتجاهات",
  childProfileTitle: "ملف رعاية الطفل",
  childProfileLead: "الحساسية والطعام والروتين. يراه المركز فقط بعد طلب مكان.",
  allergies: "الحساسية",
  epiPen: "يحمل EpiPen / حقنة تلقائية",
  foodsLike: "أطعمة يحبها",
  likes: "أشياء يحب فعلها",
  saveProfile: "حفظ الملف",
  editChild: "تعديل الملف",
  newChild: "إضافة طفل آخر",
  yes: "نعم",
  no: "لا",
  statusRequested: "تم إرسال الطلب",
  statusUnderReview: "قيد المراجعة",
  statusOffered: "تم عرض مكان",
  statusActive: "تم تأكيد المكان",
  statusDeclined: "مرفوض",
  statusWaitlist: "قائمة الانتظار",
  openChat: "فتح المحادثة",
  completeProfile: "أكمل ملف الرعاية",
  childCareCard: "بطاقة رعاية الطفل",
  noAllergies: "لا حساسية مذكورة",
  pickChild: "استخدام طفل محفوظ",
  newChildOption: "طفل جديد",
  locating: "نبحث عن رعاية مرخّصة بالقرب منك…",
  featuredNear: "أماكن هذا الشهر قرب",
};

const tl: Pack = {
  language: "Wika",
  tagline: "Lisensyadong pangangalaga, malapit sa bahay.",
  search: "Maghanap",
  explore: "Tuklasin",
  saved: "Naka-save",
  inbox: "Mensahe",
  account: "Account",
  provider: "Sentro",
  signIn: "Mag-sign in",
  signOut: "Mag-sign out",
  continueGoogle: "Magpatuloy sa Google",
  continueX: "Magpatuloy sa X",
  continueApple: "Mag-sign in gamit ang Apple",
  orEmail: "o gumamit ng email",
  email: "Email",
  password: "Password",
  name: "Pangalan",
  createAccount: "Gumawa ng account",
  haveAccount: "May account na? Mag-sign in",
  needAccount: "Kailangan ng account? Gumawa",
  loginLead: "I-save ang mga sentro, humiling ng slot, at makipag-usap sa mga guro.",
  useLocation: "Gamitin ang lokasyon ko",
  locationPh: "Lungsod o postal code",
  radius: "Radius",
  km: "km",
  map: "Mapa",
  list: "Listahan",
  sort: "Ayusin",
  sortDistance: "Distansya",
  sortPrice: "Presyo",
  sortRating: "Rating",
  sortOpen: "Bakanteng slot",
  anyAge: "Anumang edad",
  infant: "Sanggol",
  toddler: "Toddler",
  preschool: "Preschool",
  monthlyFrom: "mula",
  month: "/buwan",
  spots: "bakanteng slot",
  waitlist: "waitlist",
  licensed: "Lisensyado",
  reviews: "review",
  noResults: "Walang lisensyadong sentro sa radius na ito. Palawakin o subukan ang ibang lungsod.",
  featured: "May slot ngayong buwan malapit sa iyo",
  how: "Paano ito gumagana",
  how1t: "Magtakda ng radius",
  how1: "Maghanap mula sa bahay, trabaho, o postal code. Kilometro ang distansya.",
  how2t: "Lisensyadong childcare",
  how2: "Tingnan ang buwanang gastos, availability, at reviews bago piliin ang pinakamainam.",
  how3t: "Humiling at magbayad",
  how3: "Magpadala ng request, mag-chat, tapos magbayad ng deposito kung may alok.",
  privacyNote: "Para sa pamilyang Canadian. Hindi namin ibinebenta ang data ng bata.",
  privacy: "Privacy",
  cookies: "Cookies",
  viewListing: "Tingnan ang listing",
  book: "Humiling ng slot",
  message: "Mensahe",
  save: "I-save",
  call: "Tawag",
  hours: "Oras",
  pricing: "Presyo",
  child: "Anak",
  addChild: "Magdagdag ng anak",
  dashboard: "Ang pamilya mo",
  children: "Mga anak",
  pay: "Magbayad",
  loading: "Naglo-load",
  heroCta: "Maghanap ng daycare malapit",
  heroSub: "Bubukas ang KidEase sa iyong rehiyon. Maghanap ng lisensyadong sentro by kilometre gamit ang GPS o postal code — buong Canada.",
  popular: "Subukan",
  guestBrowse: "Mag-browse nang walang account. Mag-sign in kapag hihingi ng slot.",
  getApp: "Kunin ang app",
  provinces: "Mga lalawigan",
  regionHint: "Bubukas ang app sa iyong rehiyon. Payagan ang location, o pumili ng lalawigan.",
  centresLabel: "lisensyadong sentro",
  requestSpotTitle: "Humiling ng slot",
  sendRequest: "Ipadala ang request",
  cancel: "Kanselahin",
  myRequests: "Mga request ko",
  directions: "Direksyon",
  childProfileTitle: "Profile ng pangangalaga",
  childProfileLead: "Allergy, pagkain, at routine. Makikita lang ito ng sentro pagkatapos mong mag-request.",
  allergies: "Mga allergy",
  saveProfile: "I-save ang profile",
  yes: "Oo",
  no: "Hindi",
  statusRequested: "Naipadala ang request",
  locating: "Naghahanap ng lisensyadong pangangalaga malapit sa iyo…",
};

const it: Pack = {
  language: "Lingua",
  tagline: "Nidi autorizzati, vicino a casa.",
  search: "Cerca",
  explore: "Esplora",
  saved: "Salvati",
  inbox: "Messaggi",
  account: "Account",
  provider: "Centro",
  signIn: "Accedi",
  signOut: "Esci",
  continueGoogle: "Continua con Google",
  continueX: "Continua con X",
  continueApple: "Accedi con Apple",
  orEmail: "oppure usa l’email",
  email: "Email",
  password: "Password",
  name: "Nome",
  createAccount: "Crea account",
  haveAccount: "Hai già un account? Accedi",
  needAccount: "Serve un account? Creane uno",
  loginLead: "Salva i centri, richiedi un posto e scrivi alle educatrici.",
  useLocation: "Usa la mia posizione",
  locationPh: "Città o codice postale",
  radius: "Raggio",
  km: "km",
  map: "Mappa",
  list: "Elenco",
  sort: "Ordina",
  sortDistance: "Distanza",
  sortPrice: "Prezzo",
  sortRating: "Valutazione",
  sortOpen: "Posti liberi",
  anyAge: "Qualsiasi età",
  infant: "Neonato",
  toddler: "Bambino",
  preschool: "Prescolare",
  monthlyFrom: "da",
  month: "/mese",
  spots: "posti liberi",
  waitlist: "lista d’attesa",
  licensed: "Autorizzato",
  reviews: "recensioni",
  noResults: "Nessun centro autorizzato in questo raggio. Allarga il cerchio o prova un’altra città.",
  featured: "Posti liberi questo mese vicino a te",
  how: "Come funziona",
  how1t: "Imposta un raggio",
  how1: "Cerca da casa, dal lavoro o da un codice postale. Le distanze sono in chilometri.",
  how2t: "Strutture per l'infanzia autorizzate",
  how2: "Vedi i costi mensili, la disponibilità e le recensioni prima di scegliere la migliore.",
  how3t: "Richiedi e paga",
  how3: "Invia una richiesta, chatta con il centro, poi versa un acconto se ti offrono il posto.",
  privacyNote: "Pensato per le famiglie in Canada. Non vendiamo i dati dei bambini.",
  privacy: "Privacy",
  cookies: "Cookie",
  viewListing: "Vedi scheda",
  book: "Richiedi un posto",
  message: "Messaggio",
  save: "Salva",
  call: "Chiama",
  hours: "Orari",
  pricing: "Retta",
  child: "Bambino",
  addChild: "Aggiungi un bambino",
  dashboard: "La tua famiglia",
  children: "Bambini",
  pay: "Paga",
  loading: "Caricamento",
  heroCta: "Cerca nidi vicini",
  heroSub: "KidEase si apre sulla tua zona. Cerca centri autorizzati a chilometri con GPS o codice postale, in tutto il Canada.",
  popular: "Prova",
  guestBrowse: "Sfoglia senza account. Accedi quando vuoi richiedere un posto.",
  getApp: "Scarica l’app",
  provinces: "Province",
  regionHint: "L’app si apre sulla tua zona. Consenti la posizione o scegli una provincia.",
  centresLabel: "centri autorizzati",
  requestSpotTitle: "Richiedi un posto",
  sendRequest: "Invia richiesta",
  cancel: "Annulla",
  myRequests: "Le mie richieste",
  directions: "Indicazioni",
  childProfileTitle: "Profilo di cura",
  childProfileLead: "Allergie, cibo e routine. Il centro lo vede solo dopo la richiesta di posto.",
  allergies: "Allergie",
  saveProfile: "Salva profilo",
  yes: "Sì",
  no: "No",
  statusRequested: "Richiesta inviata",
  locating: "Cerchiamo nidi autorizzati vicino a te…",
};

const de: Pack = {
  language: "Sprache",
  tagline: "Lizenzierte Betreuung, nah am Zuhause.",
  search: "Suchen",
  explore: "Entdecken",
  saved: "Gespeichert",
  inbox: "Nachrichten",
  account: "Konto",
  provider: "Einrichtung",
  signIn: "Anmelden",
  signOut: "Abmelden",
  continueGoogle: "Weiter mit Google",
  continueX: "Weiter mit X",
  continueApple: "Mit Apple anmelden",
  orEmail: "oder E-Mail nutzen",
  email: "E-Mail",
  password: "Passwort",
  name: "Name",
  createAccount: "Konto erstellen",
  haveAccount: "Schon ein Konto? Anmelden",
  needAccount: "Konto nötig? Jetzt erstellen",
  loginLead: "Einrichtungen merken, einen Platz anfragen und mit Fachkräften schreiben.",
  useLocation: "Meinen Standort nutzen",
  locationPh: "Stadt oder Postleitzahl",
  radius: "Radius",
  km: "km",
  map: "Karte",
  list: "Liste",
  sort: "Sortieren",
  sortDistance: "Entfernung",
  sortPrice: "Preis",
  sortRating: "Bewertung",
  sortOpen: "Freie Plätze",
  anyAge: "Jedes Alter",
  infant: "Säugling",
  toddler: "Kleinkind",
  preschool: "Vorschule",
  monthlyFrom: "ab",
  month: "/Monat",
  spots: "freie Plätze",
  waitlist: "Warteliste",
  licensed: "Lizenziert",
  reviews: "Bewertungen",
  noResults: "Keine lizenzierten Einrichtungen in diesem Radius. Kreis erweitern oder andere Stadt versuchen.",
  featured: "Diesen Monat Plätze in Ihrer Nähe",
  how: "So funktioniert’s",
  how1t: "Radius setzen",
  how1: "Suche von zu Hause, der Arbeit oder einer Postleitzahl. Entfernungen in Kilometern.",
  how2t: "Lizenzierte Kinderbetreuung",
  how2: "Monatliche Kosten, Verfügbarkeit und Bewertungen prüfen, bevor Sie die beste wählen.",
  how3t: "Anfragen und zahlen",
  how3: "Platz anfragen, chatten, dann Anzahlung leisten, wenn ein Platz angeboten wird.",
  privacyNote: "Für Familien in Kanada. Wir verkaufen keine Kinderdaten.",
  privacy: "Datenschutz",
  cookies: "Cookies",
  viewListing: "Eintrag ansehen",
  book: "Platz anfragen",
  message: "Nachricht",
  save: "Speichern",
  call: "Anrufen",
  hours: "Zeiten",
  pricing: "Beiträge",
  child: "Kind",
  addChild: "Kind hinzufügen",
  dashboard: "Ihre Familie",
  children: "Kinder",
  pay: "Zahlen",
  loading: "Laden",
  heroCta: "Betreuung in der Nähe suchen",
  heroSub: "KidEase öffnet sich in Ihrer Region. Suchen Sie lizenzierte Einrichtungen per Kilometer — GPS oder Postleitzahl, ganz Kanada.",
  popular: "Ausprobieren",
  guestBrowse: "Ohne Konto stöbern. Anmelden, wenn Sie einen Platz anfragen.",
  getApp: "App holen",
  provinces: "Provinzen",
  regionHint: "Die App öffnet sich in Ihrer Region. Standort erlauben oder eine Provinz wählen.",
  centresLabel: "lizenzierte Einrichtungen",
  requestSpotTitle: "Platz anfragen",
  sendRequest: "Anfrage senden",
  cancel: "Abbrechen",
  myRequests: "Meine Anfragen",
  directions: "Route",
  childProfileTitle: "Betreuungsprofil",
  childProfileLead: "Allergien, Essen und Alltag. Die Einrichtung sieht das erst nach einer Platzanfrage.",
  allergies: "Allergien",
  saveProfile: "Profil speichern",
  yes: "Ja",
  no: "Nein",
  statusRequested: "Anfrage gesendet",
  locating: "Suche lizenzierte Betreuung in Ihrer Nähe…",
};

export const extraCopy: Record<Exclude<Locale, "en" | "fr">, Pack> = {
  zh,
  yue,
  pa,
  es,
  ar,
  tl,
  it,
  de,
};
