import { createFileRoute, Link } from "@tanstack/react-router";
import { LocateFixed, SlidersHorizontal, Sparkles } from "lucide-react";
import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { Shell } from "@/components/shell";
import { DaycareCard } from "@/components/daycare-card";
import { Button } from "@/components/ui/button";
import { searchDaycares } from "@/lib/server/daycares";
import { matchCentres } from "@/lib/server/ai";
import { reverseGeocode } from "@/lib/geo";
import { bootSearchOrigin } from "@/lib/search-origin";
import { fsaOf } from "@/lib/proximity";
import { areaPresence, presenceFreshness } from "@/lib/presence";
import { readSearchCache, searchCacheKey, writeSearchCache } from "@/lib/search-cache";
import { getDeviceLocation, hapticLight } from "@/lib/native";
import { useLivePresence } from "@/lib/use-presence";
import { trackLocation } from "@/lib/telemetry";
import { useAppStore, type SortKey } from "@/lib/store";
import { useCopy } from "@/lib/use-copy";
import { cn } from "@/lib/utils";
import { cwelccKind, hasAmenity, opensEarly, staysLate } from "@/lib/licensing";
import { ExploreSheet, type SheetSnap } from "@/components/explore-sheet";
import { LocationConsentCard } from "@/components/location-consent";
import { PlaceSearch, resolveLocationQuery } from "@/components/place-search";
import { kmToMi, miToKm, type DistanceUnit } from "@/lib/units";
import type { AgeGroup, DaycareCard as Card } from "@/lib/types";
