export const CSP_SCRIPT_HOSTS: string[];
export const CSP_CONNECT_HOSTS: string[];
export const CSP_FRAME_HOSTS: string[];
export const CSP_IMG_HOSTS: string[];
export const STYLE_NONCE_BOOT: string;
export const HTML_DOCUMENT_CACHE_CONTROL: string;
export function generateNonce(): string;
export function buildContentSecurityPolicy(nonce: string): string;
export function applyScriptNonces(html: string, nonce: string): string;
export function applyStyleNonces(html: string, nonce: string): string;
export function applyStyleNonceBoot(html: string, nonce: string): string;
export function applyDocumentNonces(html: string, nonce: string): string;
export function applyHtmlDocumentCacheHeaders(headers: Headers): void;
export function isHtmlResponse(contentType: string | null | undefined): boolean;
