import assert from "node:assert/strict";
import { readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import sharp from "sharp";
import {
  APP_FILL,
  MASKABLE_FILL,
  TAB_FILL,
  composeBuffer,
  loadTrimmedPin,
} from "./make-app-icons.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47]);

const REAL_PNGS = [
  "public/icon-192.png",
  "public/icon-512.png",
  "public/icon-1024.png",
  "public/apple-touch-icon.png",
  "public/favicon-16.png",
  "public/favicon-32.png",
  "public/favicon-48.png",
  "public/favicon-192.png",
  "public/icons/icon-180.png",
  "public/icons/icon-192.png",
  "public/icons/icon-512.png",
  "public/icons/icon-1024.png",
  "public/icons/icon-maskable-512.png",
  "public/icons/icon-maskable-1024.png",
  "public/icons/icon-foreground.png",
  "public/store/appstore-icon.png",
  "public/__grok/icon-180.png",
  "public/__grok/icon-192.png",
  "public/__grok/icon-512.png",
];

async function pinBBox(path) {
  const { data, info } = await sharp(path)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  let minX = info.width;
  let minY = info.height;
  let maxX = 0;
  let maxY = 0;
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      const o = (y * info.width + x) * info.channels;
      const r = data[o];
      const g = data[o + 1];
      const b = data[o + 2];
      const a = data[o + 3];
      const isPin = a > 10 && !(r > 245 && g > 245 && b > 245);
      if (isPin) {
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
      }
    }
  }
  return {
    width: info.width,
    height: info.height,
    pinW: maxX - minX + 1,
    pinH: maxY - minY + 1,
    fillH: (maxY - minY + 1) / info.height,
    fillW: (maxX - minX + 1) / info.width,
    channels: info.channels,
  };
}

test("app icon fill stays in the 92–96% home-screen band", () => {
  assert.ok(APP_FILL >= 0.92 && APP_FILL <= 0.96);
  assert.ok(TAB_FILL >= 0.88 && TAB_FILL <= 0.96);
  assert.ok(MASKABLE_FILL >= 0.72 && MASKABLE_FILL <= 0.82);
});

test("package.json exposes a regenerable icons script", () => {
  const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
  assert.equal(pkg.scripts.icons, "node scripts/make-app-icons.mjs");
});

test("committed app icons are real PNG bytes, not 16-byte stubs", () => {
  for (const rel of REAL_PNGS) {
    const bytes = readFileSync(join(root, rel));
    assert.ok(bytes.length > 500, `${rel} is only ${bytes.length} bytes`);
    assert.deepEqual(bytes.subarray(0, 4), PNG_MAGIC, `${rel} is not a PNG`);
    assert.notEqual(bytes.toString("utf8"), "<base64 omitted>");
  }
  assert.ok(statSync(join(root, "public/favicon.ico")).size > 200);
});

test("home-screen 512 pin dominates the tile without stretching", async () => {
  const src = await loadTrimmedPin();
  const srcAspect = src.width / src.height;
  const icon = await pinBBox(join(root, "public/icon-512.png"));
  assert.equal(icon.width, 512);
  assert.equal(icon.height, 512);
  assert.ok(icon.fillH >= 0.92, `pin height fill ${icon.fillH}`);
  assert.ok(icon.fillH <= 0.97, `pin height fill ${icon.fillH} leaves no iOS tip margin`);
  const iconAspect = icon.pinW / icon.pinH;
  assert.ok(
    Math.abs(iconAspect - srcAspect) < 0.02,
    `stretched pin ${iconAspect} vs source ${srcAspect}`,
  );
});

test("composeBuffer keeps uniform scale and the requested fill", async () => {
  const src = await loadTrimmedPin();
  const info = await composeBuffer(512, APP_FILL);
  assert.equal(info.pinH, Math.round(512 * APP_FILL));
  assert.equal(info.pinW, Math.round(info.pinH * (src.width / src.height)));
  assert.ok(info.png.length > 500);
  assert.deepEqual(info.png.subarray(0, 4), PNG_MAGIC);
});

test("/app-icon serves local generated bytes, not production", () => {
  const src = readFileSync(join(root, "src/lib/app-icon-png.ts"), "utf8");
  assert.match(src, /public.*icon-512\.png/);
  assert.doesNotMatch(src, /https:\/\/www\.kidease\.ca\/icon-512/);
});
