/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetAppRouteImport } from './routes/get-app'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TourChecklistRouteImport } from './routes/tour-checklist'
import { Route as ApiDigestRouteImport } from './routes/api/digest'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as CheckinIdRouteImport } from './routes/checkin.$id'
import { Route as DaycareSlugRouteImport } from './routes/daycare.$slug'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as PayBookingIdRouteImport } from './routes/pay.$bookingId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAppRoute = GetAppRouteImport.update({
  id: '/get-app',
  path: '/get-app',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TourChecklistRoute = TourChecklistRouteImport.update({
  id: '/tour-checklist',
  path: '/tour-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestRoute = ApiDigestRouteImport.update({
  id: '/api/digest',
  path: '/api/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinIdRoute = CheckinIdRouteImport.update({
  id: '/checkin/$id',
  path: '/checkin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DaycareSlugRoute = DaycareSlugRouteImport.update({
  id: '/daycare/$slug',
  path: '/daycare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InboxRoute,
} as any)
const PayBookingIdRoute = PayBookingIdRouteImport.update({
  id: '/pay/$bookingId',
  path: '/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/benefits': typeof BenefitsRoute
  '/claim': typeof ClaimRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/get-app': typeof GetAppRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tour-checklist': typeof TourChecklistRoute
  '/api/digest': typeof ApiDigestRoute
  '/book/$slug': typeof BookSlugRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/daycare/$slug': typeof DaycareSlugRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/benefits': typeof BenefitsRoute
  '/claim': typeof ClaimRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/get-app': typeof GetAppRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tour-checklist': typeof TourChecklistRoute
  '/api/digest': typeof ApiDigestRoute
  '/book/$slug': typeof BookSlugRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/daycare/$slug': typeof DaycareSlugRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/benefits': typeof BenefitsRoute
  '/claim': typeof ClaimRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/get-app': typeof GetAppRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/provider': typeof ProviderRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tour-checklist': typeof TourChecklistRoute
  '/api/digest': typeof ApiDigestRoute
  '/book/$slug': typeof BookSlugRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/daycare/$slug': typeof DaycareSlugRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/benefits'
    | '/claim'
    | '/compare'
    | '/contact'
    | '/get-app'
    | '/inbox'
    | '/login'
    | '/privacy'
    | '/provider'
    | '/search'
    | '/support'
    | '/team'
    | '/terms'
    | '/tour-checklist'
    | '/api/digest'
    | '/book/$slug'
    | '/checkin/$id'
    | '/daycare/$slug'
    | '/inbox/$id'
    | '/pay/$bookingId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/benefits'
    | '/claim'
    | '/compare'
    | '/contact'
    | '/get-app'
    | '/inbox'
    | '/login'
    | '/privacy'
    | '/provider'
    | '/search'
    | '/support'
    | '/team'
    | '/terms'
    | '/tour-checklist'
    | '/api/digest'
    | '/book/$slug'
    | '/checkin/$id'
    | '/daycare/$slug'
    | '/inbox/$id'
    | '/pay/$bookingId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/benefits'
    | '/claim'
    | '/compare'
    | '/contact'
    | '/get-app'
    | '/inbox'
    | '/login'
    | '/privacy'
    | '/provider'
    | '/search'
    | '/support'
    | '/team'
    | '/terms'
    | '/tour-checklist'
    | '/api/digest'
    | '/book/$slug'
    | '/checkin/$id'
    | '/daycare/$slug'
    | '/inbox/$id'
    | '/pay/$bookingId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BenefitsRoute: typeof BenefitsRoute
  ClaimRoute: typeof ClaimRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  GetAppRoute: typeof GetAppRoute
  InboxRoute: typeof InboxRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProviderRoute: typeof ProviderRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TourChecklistRoute: typeof TourChecklistRoute
  ApiDigestRoute: typeof ApiDigestRoute
  BookSlugRoute: typeof BookSlugRoute
  CheckinIdRoute: typeof CheckinIdRoute
  DaycareSlugRoute: typeof DaycareSlugRoute
  PayBookingIdRoute: typeof PayBookingIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-app': {
      id: '/get-app'
      path: '/get-app'
      fullPath: '/get-app'
      preLoaderRoute: typeof GetAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-checklist': {
      id: '/tour-checklist'
      path: '/tour-checklist'
      fullPath: '/tour-checklist'
      preLoaderRoute: typeof TourChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest': {
      id: '/api/digest'
      path: '/api/digest'
      fullPath: '/api/digest'
      preLoaderRoute: typeof ApiDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$id': {
      id: '/checkin/$id'
      path: '/checkin/$id'
      fullPath: '/checkin/$id'
      preLoaderRoute: typeof CheckinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daycare/$slug': {
      id: '/daycare/$slug'
      path: '/daycare/$slug'
      fullPath: '/daycare/$slug'
      preLoaderRoute: typeof DaycareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/pay/$bookingId': {
      id: '/pay/$bookingId'
      path: '/pay/$bookingId'
      fullPath: '/pay/$bookingId'
      preLoaderRoute: typeof PayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxIdRoute: typeof InboxIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIdRoute: InboxIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BenefitsRoute: BenefitsRoute,
  ClaimRoute: ClaimRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  GetAppRoute: GetAppRoute,
  InboxRoute: InboxRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProviderRoute: ProviderRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TourChecklistRoute: TourChecklistRoute,
  ApiDigestRoute: ApiDigestRoute,
  BookSlugRoute: BookSlugRoute,
  CheckinIdRoute: CheckinIdRoute,
  DaycareSlugRoute: DaycareSlugRoute,
  PayBookingIdRoute: PayBookingIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
