/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminContractsRouteImport } from './routes/admin-contracts'
import { Route as AppIconRouteImport } from './routes/app-icon'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as ChildcareBenefitsProgramRouteImport } from './routes/childcare-benefits-program'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetAppRouteImport } from './routes/get-app'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ImgRouteImport } from './routes/img'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetTheTeamRouteImport } from './routes/meet-the-team'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TourChecklistRouteImport } from './routes/tour-checklist'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
